"""3D roof visualizer with optional fixedboxtrick satellite underlay.

This module mirrors ``roof_visualizer.py`` data loading and KPIs, then adds a
Deck.gl ``BitmapLayer`` using the satellite image generated by
``ultralytics/fixedboxtrick.py``.
"""

from __future__ import annotations

import argparse
import base64
import json
import math
import mimetypes
import os
from typing import Any

from cea.inputlocator import InputLocator
from cea.resources.radiation import roof_visualizer as base


DEFAULT_OUTPUT_HTML = os.path.join(
    "outputs", "data", "solar-radiation", "roof_3d_layers_map_satellite.html"
)
DEFAULT_SCENARIO_SATELLITE_IMAGE_RELATIVE_PATH = os.path.join(
    "inputs", "building-geometry", "satellite_image_raw.png"
)
DEFAULT_SATELLITE_IMAGE_CANDIDATE_RELATIVE_PATHS = [
    os.path.join("ultralytics", "satellite_image_raw.png"),
    os.path.join("ultralytics", "satellite_image.png"),  # legacy fallback (may be annotated)
]
DEFAULT_SATELLITE_SIGNATURE_RELATIVE_PATH = os.path.join(
    "inputs", "building-geometry", "roof_surfaces.input_signature.json"
)
DEFAULT_SATELLITE_OPACITY = 0.8


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate a local 3D roof visualizer HTML with optional satellite underlay."
    )
    parser.add_argument("--scenario", required=True, help="Path to the CEA scenario.")
    parser.add_argument("--roof-file", default="", help="Roof surfaces GeoJSON path.")
    parser.add_argument("--output-html", default="", help="Output HTML path.")
    parser.add_argument("--map-style", default=base.DEFAULT_MAP_STYLE, help="MapLibre style URL.")
    parser.add_argument("--pv-panel", default=base.DEFAULT_PV_PANEL, help="PV panel id for PV totals CSV.")
    parser.add_argument(
        "--bar-scale-m-per-mwh",
        type=float,
        default=base.DEFAULT_BAR_SCALE_M_PER_MWH,
        help="Solar bar height scale in metres per MWh/year.",
    )
    parser.add_argument(
        "--min-bar-height-m",
        type=float,
        default=base.DEFAULT_MIN_BAR_HEIGHT_M,
        help="Minimum visible solar bar height for non-zero PV.",
    )
    parser.add_argument(
        "--bar-width-m",
        type=float,
        default=base.DEFAULT_BAR_WIDTH_M,
        help="Solar bar width in metres.",
    )
    parser.add_argument(
        "--bar-color-scale",
        choices=base.BAR_COLOR_SCALE_CHOICES,
        default=base.DEFAULT_BAR_COLOR_SCALE,
        help="Color scaling mode for solar bars.",
    )
    parser.add_argument(
        "--coordinate-precision",
        type=int,
        default=base.DEFAULT_COORDINATE_PRECISION,
        help="Decimal places for lon/lat coordinates embedded in HTML.",
    )
    parser.add_argument(
        "--flat-threshold-deg",
        type=float,
        default=base.DEFAULT_FLAT_THRESHOLD_DEG,
        help="Tilt threshold (degrees) below which roofs are classified as flat.",
    )
    parser.add_argument(
        "--satellite-image",
        default="",
        help=(
            "Path to satellite image to overlay. "
            "Default: scenario satellite_image_raw.png, then repository raw fallback."
        ),
    )
    parser.add_argument(
        "--satellite-signature",
        default="",
        help=(
            "Path to roof input signature JSON containing polygon_ring_lon_lat. "
            "Default: <scenario>/inputs/building-geometry/roof_surfaces.input_signature.json."
        ),
    )
    parser.add_argument(
        "--satellite-opacity",
        type=float,
        default=DEFAULT_SATELLITE_OPACITY,
        help="Satellite opacity between 0 and 1.",
    )
    parser.add_argument(
        "--show-satellite",
        action=argparse.BooleanOptionalAction,
        default=True,
        help="Initial visibility for the satellite layer (use --no-show-satellite to start hidden).",
    )
    return parser.parse_args()


def _default_output_html_path(scenario: str) -> str:
    return os.path.join(os.path.abspath(scenario), DEFAULT_OUTPUT_HTML)


def _resolve_repo_root() -> str:
    return os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..", ".."))


def _default_satellite_image_path(scenario: str) -> str:
    scenario_candidate = os.path.join(
        os.path.abspath(scenario),
        DEFAULT_SCENARIO_SATELLITE_IMAGE_RELATIVE_PATH,
    )
    if os.path.exists(scenario_candidate):
        return scenario_candidate

    repo_root = _resolve_repo_root()
    repo_candidates = [
        os.path.join(repo_root, relative_path)
        for relative_path in DEFAULT_SATELLITE_IMAGE_CANDIDATE_RELATIVE_PATHS
    ]
    for candidate in repo_candidates:
        if os.path.exists(candidate):
            return candidate
    return repo_candidates[0]


def _default_signature_path(scenario: str) -> str:
    return os.path.join(os.path.abspath(scenario), DEFAULT_SATELLITE_SIGNATURE_RELATIVE_PATH)


def _normalise_ring(points: Any) -> list[list[float]] | None:
    if not isinstance(points, list):
        return None

    cleaned: list[list[float]] = []
    for point in points:
        if not isinstance(point, (list, tuple)) or len(point) < 2:
            continue
        try:
            lon = float(point[0])
            lat = float(point[1])
        except (TypeError, ValueError):
            continue
        if not (math.isfinite(lon) and math.isfinite(lat)):
            continue
        cleaned.append([lon, lat])

    if len(cleaned) < 3:
        return None
    if cleaned[0] != cleaned[-1]:
        cleaned.append(cleaned[0])
    return cleaned


def _bounds_from_ring(ring: list[list[float]]) -> dict[str, float]:
    lons = [point[0] for point in ring]
    lats = [point[1] for point in ring]
    return {
        "west": float(min(lons)),
        "south": float(min(lats)),
        "east": float(max(lons)),
        "north": float(max(lats)),
    }


def _load_bounds_from_signature(signature_path: str) -> tuple[dict[str, float] | None, str | None]:
    if not signature_path or not os.path.exists(signature_path):
        return None, None
    try:
        with open(signature_path, "r", encoding="utf-8") as fp:
            payload = json.load(fp)
    except (OSError, json.JSONDecodeError):
        return None, None

    ring = _normalise_ring(payload.get("polygon_ring_lon_lat"))
    if not ring:
        return None, None
    return _bounds_from_ring(ring), signature_path


def _image_to_data_uri(image_path: str) -> str:
    with open(image_path, "rb") as fp:
        encoded = base64.b64encode(fp.read()).decode("ascii")
    mime_type = mimetypes.guess_type(image_path)[0] or "image/png"
    return f"data:{mime_type};base64,{encoded}"


def _build_satellite_payload(
    *,
    image_path: str,
    signature_path: str,
    fallback_bounds: dict[str, float],
    opacity: float,
    visible: bool,
) -> dict[str, Any]:
    payload: dict[str, Any] = {
        "available": False,
        "visible": bool(visible),
        "opacity": float(opacity),
        "image_path": image_path if image_path else None,
        "signature_path": signature_path if signature_path else None,
        "bounds": None,
        "bounds_source": None,
        "image_data_uri": None,
        "status": "Satellite image not configured.",
    }

    if not image_path or not os.path.exists(image_path):
        payload["status"] = "Satellite image file not found."
        return payload

    bounds, resolved_signature_path = _load_bounds_from_signature(signature_path)
    if bounds is not None:
        payload["bounds"] = bounds
        payload["bounds_source"] = "roof input signature"
        payload["signature_path"] = resolved_signature_path
    else:
        payload["bounds"] = fallback_bounds
        payload["bounds_source"] = "zone bounds fallback"

    try:
        payload["image_data_uri"] = _image_to_data_uri(image_path)
    except OSError:
        payload["status"] = "Satellite image could not be read."
        return payload

    payload["available"] = True
    payload["status"] = "Satellite layer ready."
    return payload


def render_html(output_path: str, payload: dict[str, Any]) -> None:
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    html = f"""<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>Roof Visualizer + Satellite</title>
  <script src="https://unpkg.com/deck.gl@latest/dist.min.js"></script>
  <script src="https://unpkg.com/maplibre-gl@latest/dist/maplibre-gl.js"></script>
  <link href="https://unpkg.com/maplibre-gl@latest/dist/maplibre-gl.css" rel="stylesheet" />
  <style>
    html, body, #map {{ margin: 0; width: 100%; height: 100%; overflow: hidden; font-family: sans-serif; }}
    #panel {{
      position: absolute; top: 12px; left: 12px; z-index: 2; width: 430px; max-height: calc(100% - 24px);
      overflow: auto; padding: 12px; box-sizing: border-box; border-radius: 10px;
      color: #e5edf6; background: rgba(10, 18, 30, 0.88); border: 1px solid rgba(180, 200, 220, 0.25);
    }}
    h1 {{ margin: 0 0 8px; font-size: 18px; }}
    label {{ display: block; margin: 8px 0; }}
    .muted {{ color: #a9b8c8; font-size: 12px; overflow-wrap: anywhere; }}
    .metrics {{ white-space: pre-line; font-family: monospace; font-size: 12px; margin-top: 10px; }}
    #details {{ white-space: pre-line; font-family: monospace; font-size: 12px; margin-top: 10px; }}
  </style>
</head>
<body>
  <div id="map"></div>
  <aside id="panel">
    <h1>Roof Visualizer + Satellite</h1>
    <div class="muted">Buildings: <span id="buildingCount"></span> | Roofs: <span id="roofCount"></span> | Bars: <span id="barCount"></span></div>
    <label><input id="satellite" type="checkbox"> Satellite image</label>
    <label><input id="zone2d" type="checkbox" checked> Zone footprints</label>
    <label><input id="zone3d" type="checkbox" checked> Zone 3D + roofs</label>
    <label><input id="zone3dOnly" type="checkbox"> Zone 3D only</label>
    <label><input id="solarBars" type="checkbox" checked> Solar bars</label>
    <div class="muted">Satellite file: <span id="satPath"></span></div>
    <div class="muted">Satellite bounds: <span id="satBounds"></span></div>
    <div class="muted">Satellite status: <span id="satStatus"></span></div>
    <div class="muted">Roof file: <span id="roofPath"></span></div>
    <div class="muted">PV file: <span id="pvPath"></span></div>
    <div class="muted">PV panel code: <span id="pvCode"></span> | Efficiency PV_n: <span id="pvEff"></span></div>
    <div id="kpiSummary" class="metrics"></div>
    <div id="details">Click a building, roof, or solar bar.</div>
  </aside>
  <script>
    const payload = {json.dumps(payload, ensure_ascii=True, separators=(",", ":"))};
    const satellitePayload = payload.satellite || {{}};
    const satelliteAvailable = Boolean(
      satellitePayload.available &&
      satellitePayload.image_data_uri &&
      satellitePayload.bounds
    );
    const satelliteDefaultVisible = satelliteAvailable && satellitePayload.visible !== false;
    const state = {{satellite: satelliteDefaultVisible, zone2d: true, zone3d: true, zone3dOnly: false, solarBars: true}};
    let selectedBuilding = null;
    const details = document.getElementById("details");
    document.getElementById("buildingCount").textContent = String((payload.zone.features || []).length);
    document.getElementById("roofCount").textContent = String((payload.roofs || []).length);
    document.getElementById("barCount").textContent = String((payload.bars || []).length);
    document.getElementById("roofPath").textContent = payload.roof_file_path || "-";
    document.getElementById("pvPath").textContent = payload.pv_source_path || "(not found)";
    document.getElementById("pvCode").textContent = payload.pv_panel_code || "(not found)";
    document.getElementById("pvEff").textContent = payload.pv_panel_efficiency == null
      ? "(not found)"
      : Number(payload.pv_panel_efficiency).toLocaleString(undefined, {{maximumFractionDigits: 6}});
    document.getElementById("satPath").textContent = satellitePayload.image_path || "(not found)";
    document.getElementById("satStatus").textContent = satellitePayload.status || "Satellite layer unavailable.";
    const satelliteToggle = document.getElementById("satellite");
    satelliteToggle.checked = satelliteDefaultVisible;
    satelliteToggle.disabled = !satelliteAvailable;

    function hasNumber(value) {{
      return value !== null && value !== undefined && Number.isFinite(Number(value));
    }}

    function n(value, digits = 2) {{
      if (!hasNumber(value)) return "n/a";
      return Number(value).toLocaleString(undefined, {{maximumFractionDigits: digits}});
    }}

    function pct(value, digits = 1) {{
      if (!hasNumber(value)) return "n/a";
      return `${{(Number(value) * 100).toLocaleString(undefined, {{maximumFractionDigits: digits}})}}%`;
    }}

    function formatBounds(bounds) {{
      if (!bounds) return "(not available)";
      const source = satellitePayload.bounds_source ? ` (${{satellitePayload.bounds_source}})` : "";
      return `W ${{n(bounds.west, 6)}} | S ${{n(bounds.south, 6)}} | E ${{n(bounds.east, 6)}} | N ${{n(bounds.north, 6)}}${{source}}`;
    }}

    document.getElementById("satBounds").textContent = formatBounds(satellitePayload.bounds);

    function normaliseBuildingName(value) {{
      const name = String(value || "").trim();
      return name || null;
    }}

    function isSelectedZoneFeature(feature) {{
      const featureName = normaliseBuildingName((feature && feature.properties && feature.properties.name) || "");
      return Boolean(featureName && selectedBuilding && featureName === selectedBuilding);
    }}

    function setSelectedBuilding(value) {{
      selectedBuilding = normaliseBuildingName(value);
      if (typeof deckgl !== "undefined" && deckgl) {{
        deckgl.setProps({{layers: layers()}});
      }}
    }}

    const orientationOrder = [
      ["flat", "Flat"],
      ["N", "North"],
      ["E", "East"],
      ["S", "South"],
      ["W", "West"]
    ];

    function formatOrientationLines(values, unit = "m2") {{
      return orientationOrder
        .map(([key, label]) => `${{label}}: ${{n((values || {{}})[key], 2)}} ${{unit}}`)
        .join("\\n");
    }}

    function formatKpiSummary() {{
      const k = payload.kpis || {{}};
      const totals = k.totals || {{}};
      const coverage = k.coverage || {{}};
      const roof = k.roof_availability || {{}};
      const quality = k.quality_flags || {{}};

      const lines = [
        "KPIs",
        "----",
        `PV area: ${{n(totals.pv_area_m2)}} m2`,
        `Installed power: ${{n(totals.installed_power_kwp, 3)}} kWp`,
        `PV generation: ${{n(totals.pv_generation_kwh)}} kWh/year (${{n(totals.pv_generation_mwh)}} MWh/year)`,
        "",
        "Coverage",
        "--------",
        `Custom roof buildings: ${{n(coverage.custom_roof_buildings, 0)}} / ${{n(coverage.total_zone_buildings, 0)}} (${{pct(coverage.custom_roof_share)}})`,
        `Buildings with PV > 0: ${{n(coverage.buildings_with_pv_positive, 0)}} (${{pct(coverage.buildings_with_pv_positive_share)}})`,
        "",
        "Roof Availability (custom roofs)",
        "-------------------------------",
        `Total available roof area: ${{n(roof.available_roof_area_total_m2)}} m2`,
        formatOrientationLines(roof.available_roof_area_by_orientation_m2, "m2"),
        "",
        "Data Quality",
        "------------",
        `Ignored or invalid roofs: ${{n(quality.invalid_or_ignored_roofs, 0)}}`,
        `Missing PV rows for zone buildings: ${{n(quality.missing_pv_rows_for_zone_buildings, 0)}}`,
        `Missing PV totals file: ${{quality.missing_pv_totals_file ? "yes" : "no"}}`,
        `Missing panel code: ${{quality.missing_panel_code ? "yes" : "no"}}`
      ];
      return lines.join("\\n");
    }}

    document.getElementById("kpiSummary").textContent = formatKpiSummary();

    function layers() {{
      const result = [];
      if (state.satellite && satelliteAvailable) {{
        const b = satellitePayload.bounds;
        result.push(new deck.BitmapLayer({{
          id: "satellite-image",
          image: satellitePayload.image_data_uri,
          bounds: [Number(b.west), Number(b.south), Number(b.east), Number(b.north)],
          opacity: Number(satellitePayload.opacity ?? {DEFAULT_SATELLITE_OPACITY}),
          pickable: false
        }}));
      }}
      if (state.zone2d) {{
        result.push(new deck.GeoJsonLayer({{
          id: "zone-2d", data: payload.zone, pickable: true, stroked: true, filled: true,
          getFillColor: f => isSelectedZoneFeature(f) ? [255, 215, 0, 110] : [50, 130, 230, 55],
          getLineColor: f => isSelectedZoneFeature(f) ? [255, 215, 0, 255] : [30, 90, 200, 210],
          getLineWidth: f => isSelectedZoneFeature(f) ? 4 : 1,
          lineWidthMinPixels: 1
        }}));
      }}
      if (state.zone3d) {{
        result.push(new deck.GeoJsonLayer({{
          id: "zone-3d", data: payload.zone, pickable: true, stroked: true, filled: true,
          extruded: true, wireframe: true, opacity: 0.35,
          getFillColor: f => isSelectedZoneFeature(f) ? [255, 215, 0, 190] : [90, 170, 245, 115],
          getLineColor: f => isSelectedZoneFeature(f) ? [255, 215, 0, 255] : [245, 248, 255, 190],
          getLineWidth: f => isSelectedZoneFeature(f) ? 4 : 1,
          getElevation: f => Number((f.properties || {{}}).viz_height_m || 8)
        }}));
        result.push(new deck.PolygonLayer({{
          id: "roofs", data: payload.roofs || [], pickable: true, stroked: true, filled: true,
          getPolygon: d => d.polygon, getFillColor: [75, 95, 125, 130],
          getLineColor: [45, 65, 95, 235], lineWidthMinPixels: 1
        }}));
      }}
      if (state.zone3dOnly) {{
        result.push(new deck.GeoJsonLayer({{
          id: "zone-3d-only", data: payload.zone, pickable: true, stroked: true, filled: true,
          extruded: true, wireframe: true, opacity: 0.42,
          getFillColor: f => isSelectedZoneFeature(f) ? [255, 215, 0, 190] : [180, 190, 205, 120],
          getLineColor: f => isSelectedZoneFeature(f) ? [255, 215, 0, 255] : [240, 244, 250, 190],
          getLineWidth: f => isSelectedZoneFeature(f) ? 4 : 1,
          getElevation: f => Number((f.properties || {{}}).viz_height_m || 8)
        }}));
      }}
      if (state.solarBars) {{
        result.push(new deck.LineLayer({{
          id: "solar-bars", data: payload.bars || [], pickable: true, widthUnits: "meters",
          getWidth: d => Number(d.bar_width_m || {base.DEFAULT_BAR_WIDTH_M}),
          getSourcePosition: d => d.source_position, getTargetPosition: d => d.target_position,
          getColor: d => [...(d.bar_colour || [255, 140, 40]), 230]
        }}));
      }}
      return result;
    }}

    const buildingMetrics = payload.building_metrics || {{}};

    function dominantOrientationFromValues(values) {{
      let bestKey = null;
      let bestValue = 0;
      for (const [key] of orientationOrder) {{
        const value = Number((values || {{}})[key] || 0);
        if (Number.isFinite(value) && value > bestValue) {{
          bestValue = value;
          bestKey = key;
        }}
      }}
      return bestValue > 0 ? bestKey : null;
    }}

    function orientationLabel(key) {{
      const match = orientationOrder.find(([itemKey]) => itemKey === key);
      return match ? match[1] : key;
    }}

    function roofOrientationKey(roof) {{
      const geometryOrientation = String((roof && roof.orientation) || "").trim();
      const validGeometryOrientation = orientationOrder.some(([key]) => key === geometryOrientation);
      if (validGeometryOrientation) return geometryOrientation;

      const buildingName = normaliseBuildingName((roof && roof.building) || "");
      const bm = buildingName ? (buildingMetrics[buildingName] || null) : null;
      return dominantOrientationFromValues((bm && bm.available_by_orientation_m2) || null);
    }}

    function roofOrientationAreaM2(roof, orientationKey) {{
      if (!orientationKey) return null;
      const buildingName = normaliseBuildingName((roof && roof.building) || "");
      if (!buildingName) return null;
      const bm = buildingMetrics[buildingName];
      if (!bm) return null;
      const values = bm.available_by_orientation_m2 || {{}};
      const area = Number(values[orientationKey]);
      return Number.isFinite(area) ? area : null;
    }}

    function formatBuildingDetails(buildingName, fallbackHeight = null) {{
      const m = buildingMetrics[buildingName];
      if (!m) {{
        return [
          "Building",
          `Name: ${{buildingName || "-"}}`,
          `Height: ${{n(fallbackHeight)}} m`,
          "No metrics available for this building."
        ].join("\\n");
      }}

      const lines = [
        "Building",
        `Name: ${{buildingName}}`,
        `Height: ${{n(m.height_m)}} m`,
        `Custom roof detected: ${{m.custom_roof_detected ? "yes" : "no"}}`,
        `Custom roofs: ${{n(m.custom_roof_count, 0)}}`,
        `Available roof area: ${{n(m.available_roof_area_m2)}} m2`,
        "PV installed area by orientation:",
        formatOrientationLines(m.pv_installed_by_orientation_m2, "m2"),
        `PV generation: ${{n(m.pv_generation_kwh)}} kWh/year`,
        `PV installed area: ${{n(m.pv_installed_area_m2)}} m2`,
        `Installed power: ${{n(m.pv_installed_power_kwp, 3)}} kWp`
      ];
      return lines.join("\\n");
    }}

    const deckgl = new deck.DeckGL({{
      container: "map", mapStyle: payload.map_style, controller: true, layers: layers(),
      initialViewState: {{latitude: payload.centre_lat, longitude: payload.centre_lon, zoom: 13, pitch: 55, bearing: -15}},
      getTooltip: info => {{
        if (!info.object) return null;
        if (info.layer.id === "roofs") {{
          const key = roofOrientationKey(info.object);
          const label = key ? orientationLabel(key) : "-";
          const areaByOrientation = roofOrientationAreaM2(info.object, key);
          return `Roof\\nBuilding: ${{info.object.building}}\\nRoof: ${{info.object.roof_id}}\\nArea: ${{n(info.object.area_m2)}} m2\\nOrientation: ${{label}}\\nBuilding area in this orientation: ${{n(areaByOrientation)}} m2`;
        }}
        if (info.layer.id === "solar-bars") {{
          const bm = buildingMetrics[info.object.building] || {{}};
          return `Solar\\nBuilding: ${{info.object.building}}\\n${{n(info.object.solar_kwh, 1)}} kWh/year\\nInstalled: ${{n(bm.pv_installed_power_kwp, 3)}} kWp`;
        }}
        const p = info.object.properties || {{}};
        const bm = buildingMetrics[p.name || ""] || {{}};
        return `Building\\nName: ${{p.name || "-"}}\\nHeight: ${{n(p.viz_height_m)}} m\\nAvailable roof: ${{n(bm.available_roof_area_m2)}} m2`;
      }},
      onClick: info => {{
        if (!info.object) return;
        if (info.layer.id === "roofs") {{
          const buildingName = info.object.building || "-";
          setSelectedBuilding(buildingName);
          details.textContent = formatBuildingDetails(buildingName);
          return;
        }} else if (info.layer.id === "solar-bars") {{
          setSelectedBuilding(info.object.building);
          return;
        }} else {{
          const p = info.object.properties || {{}};
          const buildingName = p.name || "-";
          setSelectedBuilding(buildingName);
          details.textContent = formatBuildingDetails(buildingName, p.viz_height_m);
        }}
      }}
    }});

    for (const id of Object.keys(state)) {{
      const element = document.getElementById(id);
      if (!element) continue;
      element.addEventListener("change", event => {{
        state[id] = Boolean(event.target.checked);
        deckgl.setProps({{layers: layers()}});
      }});
    }}
  </script>
</body>
</html>
"""
    with open(output_path, "w", encoding="utf-8") as fp:
        fp.write(html)


def main() -> None:
    args = parse_args()
    if args.bar_scale_m_per_mwh <= 0:
        raise ValueError("--bar-scale-m-per-mwh must be greater than zero.")
    if args.min_bar_height_m < 0:
        raise ValueError("--min-bar-height-m must be non-negative.")
    if args.bar_width_m <= 0:
        raise ValueError("--bar-width-m must be greater than zero.")
    if args.coordinate_precision < 0:
        raise ValueError("--coordinate-precision must be non-negative.")
    if args.flat_threshold_deg < 0:
        raise ValueError("--flat-threshold-deg must be non-negative.")
    if args.satellite_opacity < 0 or args.satellite_opacity > 1:
        raise ValueError("--satellite-opacity must be between 0 and 1.")

    scenario = os.path.abspath(args.scenario)
    if not os.path.isdir(scenario):
        raise NotADirectoryError(f"Scenario folder does not exist: {scenario}")

    locator = InputLocator(scenario)
    roof_file_path = base._resolve_path(base._default_roof_file_path(scenario), args.roof_file)
    roofs, roof_stats, roof_quality = base._load_roofs(
        roof_file_path=roof_file_path,
        precision=args.coordinate_precision,
        flat_threshold_deg=float(args.flat_threshold_deg),
    )
    zone, zone_centroids, centre, bounds, zone_heights_by_building, zone_buildings = base._load_zone_payload(
        locator=locator,
        roof_stats=roof_stats,
        precision=args.coordinate_precision,
    )

    pv_metrics_by_building, pv_source_path = base._load_pv_metrics_by_building(locator, args.pv_panel)
    pv_panel_efficiency, pv_panel_code = base._load_pv_panel_efficiency(locator, args.pv_panel)
    roof_availability_by_building, _, roof_availability_source_path = base._load_panel_placement_orientation_by_building(
        locator, args.pv_panel
    )

    solar_by_building = {
        building: float(metrics.get("E_PV_gen_kWh", 0.0))
        for building, metrics in pv_metrics_by_building.items()
    }
    bars = base._build_solar_bars(
        roof_stats=roof_stats,
        zone_centroids=zone_centroids,
        zone_heights_by_building=zone_heights_by_building,
        solar_by_building_kwh=solar_by_building,
        bar_color_scale=str(args.bar_color_scale),
        bar_scale_m_per_mwh=float(args.bar_scale_m_per_mwh),
        min_bar_height_m=float(args.min_bar_height_m),
        bar_width_m=float(args.bar_width_m),
        precision=args.coordinate_precision,
    )
    _, bar_color_distribution = base._build_bar_color_ratios(
        solar_by_building_kwh=solar_by_building,
        bar_color_scale=str(args.bar_color_scale),
    )
    kpis, building_metrics = base._build_decision_metrics(
        zone_buildings=zone_buildings,
        zone_heights_by_building=zone_heights_by_building,
        roof_stats=roof_stats,
        roof_quality=roof_quality,
        pv_metrics_by_building=pv_metrics_by_building,
        pv_source_path=pv_source_path,
        pv_panel_efficiency=pv_panel_efficiency,
        pv_panel_code=pv_panel_code,
        roof_availability_by_building=roof_availability_by_building,
        roof_availability_source_path=roof_availability_source_path,
    )

    scenario_bounds = {
        "west": bounds[0],
        "south": bounds[1],
        "east": bounds[2],
        "north": bounds[3],
    }
    satellite_image_path = base._resolve_path(_default_satellite_image_path(scenario), args.satellite_image)
    satellite_signature_path = base._resolve_path(_default_signature_path(scenario), args.satellite_signature)
    satellite_payload = _build_satellite_payload(
        image_path=satellite_image_path,
        signature_path=satellite_signature_path,
        fallback_bounds=scenario_bounds,
        opacity=float(args.satellite_opacity),
        visible=bool(args.show_satellite),
    )

    payload = {
        "scenario": scenario,
        "pv_panel": str(args.pv_panel),
        "pv_panel_code": pv_panel_code,
        "pv_panel_efficiency": pv_panel_efficiency,
        "flat_threshold_deg": float(args.flat_threshold_deg),
        "bar_color_scale": str(args.bar_color_scale),
        "bar_color_distribution": bar_color_distribution,
        "map_style": args.map_style,
        "zone": zone,
        "roofs": roofs,
        "bars": bars,
        "kpis": kpis,
        "building_metrics": building_metrics,
        "roof_quality": roof_quality,
        "centre_lat": centre[0],
        "centre_lon": centre[1],
        "bounds": scenario_bounds,
        "roof_file_path": roof_file_path,
        "pv_source_path": pv_source_path,
        "roof_availability_source_path": roof_availability_source_path,
        "satellite": satellite_payload,
    }

    output_path = base._resolve_path(_default_output_html_path(scenario), args.output_html)
    render_html(output_path, payload)
    print("[ok] Roof visualizer with satellite generated.")
    print(f"Buildings loaded: {len(zone.get('features', []))}")
    print(f"Roofs loaded: {len(roofs)}")
    print(f"Solar bars loaded: {len(bars)}")
    print(f"Bar color scale: {args.bar_color_scale}")
    print(f"PV source: {pv_source_path or '(not found)'}")
    print(f"Roof availability source: {roof_availability_source_path or '(not found)'}")
    print(f"PV panel efficiency (PV_n): {pv_panel_efficiency if pv_panel_efficiency is not None else '(not found)'}")
    print(f"Satellite status: {satellite_payload.get('status')}")
    print(f"Satellite file: {satellite_payload.get('image_path') or '(not found)'}")
    print(f"Satellite bounds source: {satellite_payload.get('bounds_source') or '(none)'}")
    print(f"Output HTML: {output_path}")


if __name__ == "__main__":
    main()
