"""
Standalone layered visualiser for UCEA roof outputs.

Layers:
1) OpenStreetMap footprints in the selected zone.
2) Satellite image generated by fixedboxtilingextension_v3 (if available).
3) OpenStreetMap 3D extrusions plus generated roof surfaces.
4) OpenStreetMap 3D extrusions only (before roof overlay).
5) Solar-capacity bars (from PV totals).
"""

from __future__ import annotations

import argparse
import base64
import hashlib
import io
import json
import os
import re
import time
from typing import Any

import numpy as np
import requests
from cea.inputlocator import InputLocator
from pyproj import Transformer


DEFAULT_MAP_STYLE = "https://basemaps.cartocdn.com/gl/positron-gl-style/style.json"
DEFAULT_ROOF_FILE = os.path.join("inputs", "building-geometry", "roof_surfaces.geojson")
DEFAULT_SATELLITE_FILE = os.path.join("inputs", "building-geometry", "satellite_image.png")
DEFAULT_OUTPUT_HTML = os.path.join("outputs", "data", "solar-radiation", "roof_3d_layers_map.html")
DEFAULT_OSM_HEIGHT_M = 8.0
DEFAULT_PV_PANEL = "PV1"
DEFAULT_BAR_SCALE_M_PER_MWH = 0.15
DEFAULT_MIN_BAR_HEIGHT_M = 1.5
DEFAULT_BAR_WIDTH_M = 9.0
DEFAULT_BAR_BASE_OFFSET_M = 0.4
OVERPASS_ENDPOINTS = [
    "https://overpass-api.de/api/interpreter",
    "https://lz4.overpass-api.de/api/interpreter",
    "https://overpass.kumi.systems/api/interpreter",
]
OVERPASS_RETRIES_PER_ENDPOINT = 3
OVERPASS_TIMEOUT_SECONDS = 120


def _import_geopandas():
    try:
        import geopandas as gpd  # type: ignore
    except ModuleNotFoundError as exc:
        raise ModuleNotFoundError(
            "Missing dependency 'geopandas'. Install project dependencies and retry."
        ) from exc
    return gpd


def _import_shapely():
    try:
        from shapely.geometry import Polygon  # type: ignore
        from shapely.geometry import shape as shapely_shape  # type: ignore
        from shapely.ops import unary_union  # type: ignore
    except ModuleNotFoundError as exc:
        raise ModuleNotFoundError(
            "Missing dependency 'shapely'. Install project dependencies and retry."
        ) from exc
    return Polygon, shapely_shape, unary_union


def _import_pillow_image():
    try:
        from PIL import Image  # type: ignore
    except ModuleNotFoundError as exc:
        raise ModuleNotFoundError(
            "Missing dependency 'Pillow'. Install project dependencies and retry."
        ) from exc
    return Image


def _import_wmts():
    try:
        from owslib.wmts import WebMapTileService  # type: ignore
    except ModuleNotFoundError as exc:
        raise ModuleNotFoundError(
            "Missing dependency 'owslib'. Install project dependencies and retry."
        ) from exc
    return WebMapTileService


def _import_pandas():
    try:
        import pandas as pd  # type: ignore
    except ModuleNotFoundError as exc:
        raise ModuleNotFoundError(
            "Missing dependency 'pandas'. Install project dependencies and retry."
        ) from exc
    return pd


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate a standalone layered roof visualisation HTML from UCEA outputs."
    )
    parser.add_argument("--scenario", required=True, help="Path to the CEA scenario.")
    parser.add_argument(
        "--roof-file",
        default="",
        help=(
            "Roof surfaces GeoJSON path. Default: "
            "<scenario>/inputs/building-geometry/roof_surfaces.geojson"
        ),
    )
    parser.add_argument(
        "--satellite-image",
        default="",
        help=(
            "Satellite image path from fixedboxtilingextension_v3. Default: "
            "<scenario>/inputs/building-geometry/satellite_image.png"
        ),
    )
    parser.add_argument(
        "--output-html",
        default="",
        help=(
            "Output HTML path. Default: "
            "<scenario>/outputs/data/solar-radiation/roof_3d_layers_map.html"
        ),
    )
    parser.add_argument(
        "--map-style",
        default=DEFAULT_MAP_STYLE,
        help="MapLibre style URL for deck.gl background.",
    )
    parser.add_argument(
        "--pv-panel",
        default=DEFAULT_PV_PANEL,
        help="PV panel id used to read PV totals CSV (default: PV1).",
    )
    parser.add_argument(
        "--bar-scale-m-per-mwh",
        type=float,
        default=DEFAULT_BAR_SCALE_M_PER_MWH,
        help=f"Metres per MWh/year for solar bars (default: {DEFAULT_BAR_SCALE_M_PER_MWH}).",
    )
    parser.add_argument(
        "--min-bar-height-m",
        type=float,
        default=DEFAULT_MIN_BAR_HEIGHT_M,
        help=f"Minimum visible bar height for non-zero capacity (default: {DEFAULT_MIN_BAR_HEIGHT_M}).",
    )
    parser.add_argument(
        "--bar-width-m",
        type=float,
        default=DEFAULT_BAR_WIDTH_M,
        help=f"Solar bar width in metres (default: {DEFAULT_BAR_WIDTH_M}).",
    )
    return parser.parse_args()


def _ordered_ring_from_points_3d(points_3d: list[list[float]]) -> list[list[float]] | None:
    if len(points_3d) < 3:
        return None

    cleaned: list[list[float]] = []
    for point in points_3d:
        if not isinstance(point, list) or len(point) < 3:
            continue
        cleaned.append([float(point[0]), float(point[1]), float(point[2])])

    if len(cleaned) < 3:
        return None

    if cleaned[0] == cleaned[-1]:
        cleaned = cleaned[:-1]
    if len(cleaned) < 3:
        return None

    pts = np.unique(np.round(np.asarray(cleaned, dtype=float), 9), axis=0)
    if pts.shape[0] < 3:
        return None

    centroid = np.mean(pts, axis=0)
    centered = pts - centroid
    _, _, vh = np.linalg.svd(centered, full_matrices=False)

    axis_u = vh[0]
    normal = vh[2]
    axis_v = np.cross(normal, axis_u)
    norm_u = np.linalg.norm(axis_u)
    norm_v = np.linalg.norm(axis_v)
    if norm_u == 0.0 or norm_v == 0.0:
        return None
    axis_u = axis_u / norm_u
    axis_v = axis_v / norm_v

    uv = np.column_stack([np.dot(centered, axis_u), np.dot(centered, axis_v)])
    angles = np.arctan2(uv[:, 1], uv[:, 0])
    order = np.argsort(angles)
    ordered = pts[order]
    if ordered.shape[0] < 3:
        return None

    ring = ordered.tolist()
    ring.append(ordered[0].tolist())
    return [[float(p[0]), float(p[1]), float(p[2])] for p in ring]


def parse_geojson_crs_name(geojson_obj: dict[str, Any], fallback_crs: str) -> str:
    crs_obj = geojson_obj.get("crs")
    if isinstance(crs_obj, dict):
        props = crs_obj.get("properties")
        if isinstance(props, dict):
            name = props.get("name")
            if isinstance(name, str) and name.strip():
                return name.strip()
    return fallback_crs


def _iter_polygon_rings(geometry_type: str, coordinates: list[Any]) -> list[list[list[float]]]:
    rings: list[list[list[float]]] = []
    if geometry_type == "Polygon":
        if coordinates and isinstance(coordinates[0], list):
            rings.append(coordinates[0])
    elif geometry_type == "MultiPolygon":
        for polygon in coordinates:
            if not isinstance(polygon, list) or not polygon:
                continue
            exterior = polygon[0]
            if isinstance(exterior, list):
                rings.append(exterior)
    return rings


def default_roof_file_path(scenario: str) -> str:
    return os.path.join(os.path.abspath(scenario), DEFAULT_ROOF_FILE)


def default_satellite_image_path(scenario: str) -> str:
    return os.path.join(os.path.abspath(scenario), DEFAULT_SATELLITE_FILE)


def default_output_html_path(scenario: str) -> str:
    return os.path.join(os.path.abspath(scenario), DEFAULT_OUTPUT_HTML)


def resolve_roof_file_path(scenario: str, roof_file_arg: str) -> str:
    if roof_file_arg.strip():
        return os.path.abspath(roof_file_arg.strip())
    return default_roof_file_path(scenario)


def resolve_satellite_image_path(scenario: str, image_arg: str) -> str:
    if image_arg.strip():
        return os.path.abspath(image_arg.strip())

    candidates = [
        default_satellite_image_path(scenario),
        os.path.join(os.path.dirname(default_roof_file_path(scenario)), "satellite_image.png"),
    ]
    for candidate in candidates:
        if os.path.exists(candidate):
            return candidate
    return candidates[0]


def resolve_output_html_path(scenario: str, output_arg: str) -> str:
    if output_arg.strip():
        return os.path.abspath(output_arg.strip())
    return default_output_html_path(scenario)


def _parse_height_m(value: Any) -> float | None:
    if value is None:
        return None
    text = str(value).strip().lower()
    if not text:
        return None
    text = text.replace(",", ".")
    match = re.search(r"-?\d+(\.\d+)?", text)
    if match is None:
        return None
    try:
        parsed = float(match.group(0))
    except ValueError:
        return None
    return parsed if parsed > 0 else None


def _parse_levels_to_height_m(levels_value: Any) -> float | None:
    levels = _parse_height_m(levels_value)
    if levels is None:
        return None
    return max(3.0, levels * 3.0)


def _load_zone_site_polygon_wgs84(locator: InputLocator):
    gpd = _import_geopandas()
    Polygon, _, unary_union = _import_shapely()

    site_path = locator.get_site_polygon()
    if not os.path.exists(site_path):
        raise FileNotFoundError(f"Site polygon not found: {site_path}")

    site_gdf = gpd.read_file(site_path)
    site_gdf = site_gdf[~site_gdf.geometry.is_empty & site_gdf.geometry.notna()].copy()
    if site_gdf.empty:
        raise ValueError("Site polygon is empty.")

    site_wgs84 = site_gdf.to_crs(epsg=4326)
    site_union = unary_union(site_wgs84.geometry.values.tolist())
    if site_union.is_empty:
        raise ValueError("Site polygon is empty after CRS conversion.")
    if not isinstance(site_union, Polygon) and site_union.geom_type != "MultiPolygon":
        raise ValueError("Site polygon geometry type is not polygonal.")
    return site_union


def _site_bounds(site_polygon) -> tuple[float, float, float, float]:
    minx, miny, maxx, maxy = site_polygon.bounds
    return float(minx), float(miny), float(maxx), float(maxy)


def _wmts_get_tile_indices(xmin: float, ymin: float, xmax: float, ymax: float, matrix) -> tuple[int, int, int, int]:
    tile_size = matrix.tilewidth * matrix.scaledenominator * 0.28e-3
    origin_x, origin_y = matrix.topleftcorner
    col_min = int((xmin - origin_x) // tile_size)
    col_max = int((xmax - origin_x) // tile_size)
    row_min = int((origin_y - ymax) // tile_size)
    row_max = int((origin_y - ymin) // tile_size)
    return col_min, col_max, row_min, row_max


def _retrieve_satellite_image_from_bbox(
    top_left_corner_3763: tuple[float, float],
    bottom_right_corner_3763: tuple[float, float],
    tile_cache_dir: str,
) -> np.ndarray:
    WebMapTileService = _import_wmts()
    Image = _import_pillow_image()

    wmts_url = (
        "https://cartografia.dgterritorio.gov.pt/ortos2018/service"
        "?service=WMTS&request=GetCapabilities"
    )
    wmts = WebMapTileService(wmts_url)
    layer = "Ortos2018-RGB"
    tile_matrix_set = "PTTM_06"
    zoom_level = "14"
    matrix = wmts.tilematrixsets[tile_matrix_set].tilematrix[zoom_level]
    res = matrix.scaledenominator * 0.28e-3
    tile_size_m = matrix.tilewidth * res

    xmin, ymax = top_left_corner_3763
    xmax, ymin = bottom_right_corner_3763
    col_min, col_max, row_min, row_max = _wmts_get_tile_indices(xmin, ymin, xmax, ymax, matrix)
    n_rows = row_max + 1 - row_min
    n_cols = col_max + 1 - col_min
    processed_blocks = np.empty((n_rows, n_cols), dtype=object)

    os.makedirs(tile_cache_dir, exist_ok=True)
    for row in range(row_min, row_max + 1):
        for col in range(col_min, col_max + 1):
            tile_filename = os.path.join(tile_cache_dir, f"tile_{zoom_level}_{row}_{col}.png")
            if os.path.exists(tile_filename):
                img_array = np.array(Image.open(tile_filename).convert("RGB"))
            else:
                tile = wmts.gettile(
                    layer=layer,
                    tilematrixset=tile_matrix_set,
                    tilematrix=zoom_level,
                    row=row,
                    column=col,
                    format="image/png",
                )
                img = Image.open(io.BytesIO(tile.read())).convert("RGB")
                img.save(tile_filename)
                img_array = np.array(img)
            processed_blocks[row - row_min, col - col_min] = {"img": img_array}

    block_h, block_w = processed_blocks[0, 0]["img"].shape[:2]
    stitched = np.zeros((n_rows * block_h, n_cols * block_w, 3), dtype=np.uint8)
    for row in range(n_rows):
        for col in range(n_cols):
            stitched[row * block_h:(row + 1) * block_h, col * block_w:(col + 1) * block_w] = processed_blocks[row, col]["img"]

    origin_x = matrix.topleftcorner[0] + col_min * tile_size_m
    origin_y = matrix.topleftcorner[1] - row_min * tile_size_m

    col_start = int(round((xmin - origin_x) / res))
    row_start = int(round((origin_y - ymax) / res))
    col_end = int(round((xmax - origin_x) / res))
    row_end = int(round((origin_y - ymin) / res))
    return stitched[row_start:row_end, col_start:col_end, :]


def _ensure_matching_satellite_image(
    scenario: str,
    requested_satellite_path: str,
    roof_file_path: str,
    site_bounds_wgs84: tuple[float, float, float, float],
) -> str:
    west, south, east, north = site_bounds_wgs84
    target_path = requested_satellite_path
    if not os.path.isabs(target_path):
        target_path = os.path.abspath(target_path)
    os.makedirs(os.path.dirname(target_path), exist_ok=True)

    must_regenerate = not os.path.exists(target_path)
    if os.path.exists(target_path) and os.path.exists(roof_file_path):
        sat_mtime = os.path.getmtime(target_path)
        roof_mtime = os.path.getmtime(roof_file_path)
        if sat_mtime < roof_mtime:
            must_regenerate = True

    if not must_regenerate:
        return target_path

    print("[info] Generating scenario-matching satellite image from WMTS...")
    transformer = Transformer.from_crs("EPSG:4326", "EPSG:3763", always_xy=True)
    tl_x, tl_y = transformer.transform(west, north)
    br_x, br_y = transformer.transform(east, south)
    top_left = (float(tl_x), float(tl_y))
    bottom_right = (float(br_x), float(br_y))
    tile_cache_dir = os.path.join(os.path.abspath(os.path.dirname(__file__)), "cache", "tiles")

    image = _retrieve_satellite_image_from_bbox(
        top_left_corner_3763=top_left,
        bottom_right_corner_3763=bottom_right,
        tile_cache_dir=tile_cache_dir,
    )
    Image = _import_pillow_image()
    Image.fromarray(image).save(target_path)
    print(f"[ok] Satellite image generated: {target_path}")
    return target_path


def _fetch_osm_buildings_for_site(site_polygon, cache_dir: str) -> dict[str, Any]:
    _, shapely_shape, _ = _import_shapely()

    west, south, east, north = _site_bounds(site_polygon)
    query = (
        "[out:json][timeout:180];"
        f"(way[\"building\"]({south},{west},{north},{east});"
        f"relation[\"building\"]({south},{west},{north},{east}););"
        "out body;>;out skel qt;"
    )

    os.makedirs(cache_dir, exist_ok=True)
    key = hashlib.md5(f"{south:.8f}|{west:.8f}|{north:.8f}|{east:.8f}".encode("utf-8")).hexdigest()
    cache_path = os.path.join(cache_dir, f"osm_buildings_{key}.json")
    if os.path.exists(cache_path):
        with open(cache_path, "r", encoding="utf-8") as fp:
            return json.load(fp)

    fetch_errors: list[str] = []
    data: dict[str, Any] | None = None
    for endpoint in OVERPASS_ENDPOINTS:
        for attempt in range(1, OVERPASS_RETRIES_PER_ENDPOINT + 1):
            try:
                response = requests.post(endpoint, data=query, timeout=OVERPASS_TIMEOUT_SECONDS)
                response.raise_for_status()
                data = response.json()
                print(f"[info] OSM buildings fetched via: {endpoint}")
                break
            except requests.RequestException as exc:
                fetch_errors.append(f"{endpoint} [attempt {attempt}]: {exc}")
                if attempt < OVERPASS_RETRIES_PER_ENDPOINT:
                    sleep_seconds = 1.5 * attempt
                    print(
                        f"[warn] Overpass request failed ({endpoint}, attempt {attempt}/"
                        f"{OVERPASS_RETRIES_PER_ENDPOINT}). Retrying in {sleep_seconds:.1f}s..."
                    )
                    time.sleep(sleep_seconds)
                continue
            except ValueError as exc:
                fetch_errors.append(f"{endpoint} [attempt {attempt}]: invalid JSON ({exc})")
                continue
        if data is not None:
            break

    if data is None:
        joined = "\n".join(fetch_errors) if fetch_errors else "(no request details)"
        raise RuntimeError(
            "Could not fetch OSM buildings from Overpass endpoints.\n"
            f"Bounding box: south={south:.6f}, west={west:.6f}, north={north:.6f}, east={east:.6f}\n"
            "Tried endpoints:\n"
            f"{chr(10).join(OVERPASS_ENDPOINTS)}\n"
            "Request errors:\n"
            f"{joined}"
        )

    nodes = {
        el["id"]: (float(el["lon"]), float(el["lat"]))
        for el in data.get("elements", [])
        if el.get("type") == "node"
    }

    raw_features: list[dict[str, Any]] = []
    for element in data.get("elements", []):
        if element.get("type") != "way":
            continue
        node_ids = element.get("nodes", [])
        coords = [nodes[nid] for nid in node_ids if nid in nodes]
        if len(coords) < 3:
            continue
        raw_features.append(
            {
                "type": "Feature",
                "properties": {"osm_id": str(element.get("id", "")), **element.get("tags", {})},
                "geometry": {"type": "Polygon", "coordinates": [coords]},
            }
        )

    filtered_features: list[dict[str, Any]] = []
    for feature in raw_features:
        try:
            geom = shapely_shape(feature["geometry"])
        except Exception:
            continue
        if geom.is_empty:
            continue
        if not geom.intersects(site_polygon):
            continue
        filtered_features.append(feature)

    feature_collection = {"type": "FeatureCollection", "features": filtered_features}
    with open(cache_path, "w", encoding="utf-8") as fp:
        json.dump(feature_collection, fp, ensure_ascii=False, indent=2)
    return feature_collection


def _load_roof_surfaces(roof_file_path: str) -> list[dict[str, Any]]:
    if not os.path.exists(roof_file_path):
        raise FileNotFoundError(f"Roof surfaces file not found: {roof_file_path}")

    with open(roof_file_path, "r", encoding="utf-8") as fp:
        roof_obj = json.load(fp)

    if not isinstance(roof_obj, dict) or roof_obj.get("type") != "FeatureCollection":
        raise ValueError(f"Roof file is not a FeatureCollection: {roof_file_path}")

    source_crs = parse_geojson_crs_name(roof_obj, fallback_crs="EPSG:32629")
    transformer = Transformer.from_crs(source_crs, "EPSG:4326", always_xy=True)

    roofs: list[dict[str, Any]] = []
    features = roof_obj.get("features", [])
    if not isinstance(features, list):
        return roofs

    for feature in features:
        if not isinstance(feature, dict):
            continue
        properties = feature.get("properties", {})
        geometry = feature.get("geometry", {})
        if not isinstance(properties, dict) or not isinstance(geometry, dict):
            continue

        geometry_type = str(geometry.get("type", ""))
        coordinates = geometry.get("coordinates")
        if not isinstance(coordinates, list):
            continue

        building_name = str(properties.get("building", "")).strip()
        roof_id = str(properties.get("roof_id", "")).strip()
        rings = _iter_polygon_rings(geometry_type, coordinates)
        for ring in rings:
            if not isinstance(ring, list) or len(ring) < 3:
                continue
            points_wgs84: list[list[float]] = []
            valid = True
            for point in ring:
                if not isinstance(point, list) or len(point) < 3:
                    valid = False
                    break
                x = float(point[0])
                y = float(point[1])
                z = float(point[2])
                lon, lat = transformer.transform(x, y)
                points_wgs84.append([float(lon), float(lat), z])
            if not valid:
                continue

            ordered_ring = _ordered_ring_from_points_3d(points_wgs84)
            if ordered_ring is None:
                continue

            z_values = [pt[2] for pt in ordered_ring]
            roofs.append(
                {
                    "building": building_name,
                    "roof_id": roof_id,
                    "polygon": ordered_ring,
                    "z_min": float(min(z_values)),
                    "z_max": float(max(z_values)),
                    "z_mean": float(sum(z_values) / max(1, len(z_values))),
                }
            )
    return roofs


def _apply_osm_heights(osm_geojson: dict[str, Any], roofs: list[dict[str, Any]]) -> dict[str, Any]:
    Polygon, shapely_shape, _ = _import_shapely()

    roof_polys = []
    for roof in roofs:
        polygon_coords = roof.get("polygon", [])
        if not isinstance(polygon_coords, list) or len(polygon_coords) < 4:
            continue
        coords_2d = [(float(p[0]), float(p[1])) for p in polygon_coords if isinstance(p, list) and len(p) >= 2]
        if len(coords_2d) < 4:
            continue
        try:
            poly = Polygon(coords_2d)
        except Exception:
            continue
        if poly.is_empty:
            continue
        roof_polys.append((poly, float(roof.get("z_min", DEFAULT_OSM_HEIGHT_M))))

    features = osm_geojson.get("features", [])
    if not isinstance(features, list):
        return osm_geojson

    for feature in features:
        if not isinstance(feature, dict):
            continue
        geometry = feature.get("geometry")
        props = feature.get("properties")
        if not isinstance(geometry, dict) or not isinstance(props, dict):
            continue
        try:
            osm_poly = shapely_shape(geometry)
        except Exception:
            continue
        if osm_poly.is_empty:
            continue

        height_candidates = []
        for roof_poly, roof_zmin in roof_polys:
            if roof_poly.intersects(osm_poly):
                height_candidates.append(roof_zmin)

        height_tag = _parse_height_m(props.get("height"))
        level_height = _parse_levels_to_height_m(props.get("building:levels"))

        if height_candidates:
            roof_match_height = float(np.median(np.asarray(height_candidates, dtype=float)))
            viz_height = max(3.0, roof_match_height)
        elif height_tag is not None:
            viz_height = max(3.0, height_tag)
        elif level_height is not None:
            viz_height = max(3.0, level_height)
        else:
            viz_height = DEFAULT_OSM_HEIGHT_M

        props["viz_height_m"] = float(viz_height)
        props["osm_id"] = str(props.get("osm_id", ""))
    return osm_geojson


def _image_file_to_data_uri(image_path: str) -> str:
    if not os.path.exists(image_path):
        return ""
    ext = os.path.splitext(image_path)[1].lower()
    mime = "image/png"
    if ext in [".jpg", ".jpeg"]:
        mime = "image/jpeg"
    elif ext == ".webp":
        mime = "image/webp"
    with open(image_path, "rb") as fp:
        encoded = base64.b64encode(fp.read()).decode("ascii")
    return f"data:{mime};base64,{encoded}"


def _site_centre(site_polygon) -> tuple[float, float]:
    centroid = site_polygon.centroid
    return float(centroid.y), float(centroid.x)


def _candidate_pv_totals_paths(locator: InputLocator, pv_panel: str) -> list[str]:
    panel = str(pv_panel).strip()
    if not panel:
        panel = DEFAULT_PV_PANEL
    candidates: list[str] = []
    if panel.upper().startswith("PV_"):
        panel_no_prefix = panel[3:]
    else:
        panel_no_prefix = panel

    candidates.append(locator.PV_total_buildings(panel_no_prefix))
    manual_path = os.path.join(locator.solar_potential_folder(), f"PV_{panel_no_prefix}_total_buildings.csv")
    if manual_path not in candidates:
        candidates.append(manual_path)
    return candidates


def _load_solar_capacity_by_building(locator: InputLocator, pv_panel: str) -> tuple[dict[str, float], str]:
    pd = _import_pandas()
    for path in _candidate_pv_totals_paths(locator, pv_panel):
        if not os.path.exists(path):
            continue
        try:
            totals = pd.read_csv(path)
        except Exception:
            continue
        if "name" not in totals.columns or "E_PV_gen_kWh" not in totals.columns:
            continue
        totals = totals.copy()
        totals["name"] = totals["name"].astype(str)
        totals["E_PV_gen_kWh"] = pd.to_numeric(totals["E_PV_gen_kWh"], errors="coerce").fillna(0.0)
        return dict(zip(totals["name"], totals["E_PV_gen_kWh"])), path
    return {}, ""


def _load_zone_centroids_wgs84(locator: InputLocator) -> dict[str, list[float]]:
    gpd = _import_geopandas()
    zone_path = locator.get_zone_geometry()
    if not os.path.exists(zone_path):
        return {}
    zone = gpd.read_file(zone_path)
    if "name" not in zone.columns:
        return {}
    zone = zone[~zone.geometry.is_empty & zone.geometry.notna()].copy()
    if zone.empty:
        return {}
    zone["name"] = zone["name"].astype(str)
    zone_wgs84 = zone.to_crs(epsg=4326)
    result: dict[str, list[float]] = {}
    for _, row in zone_wgs84.iterrows():
        c = row.geometry.centroid
        result[str(row["name"])] = [float(c.x), float(c.y)]
    return result


def _map_colour(value: float, value_max: float, low: tuple[int, int, int], high: tuple[int, int, int]) -> list[int]:
    if value_max <= 0:
        ratio = 0.0
    else:
        ratio = max(0.0, min(1.0, value / value_max))
    return [
        int(low[0] + ratio * (high[0] - low[0])),
        int(low[1] + ratio * (high[1] - low[1])),
        int(low[2] + ratio * (high[2] - low[2])),
    ]


def _build_solar_bars_payload(
    roofs_payload: list[dict[str, Any]],
    solar_by_building_kwh: dict[str, float],
    zone_centroids_wgs84: dict[str, list[float]],
    bar_scale_m_per_mwh: float,
    min_bar_height_m: float,
    bar_width_m: float,
) -> list[dict[str, Any]]:
    if not solar_by_building_kwh:
        return []

    roof_stats: dict[str, dict[str, float]] = {}
    for roof in roofs_payload:
        building = str(roof.get("building", "")).strip()
        polygon = roof.get("polygon", [])
        if not building or not isinstance(polygon, list) or len(polygon) < 4:
            continue
        coords = [p for p in polygon if isinstance(p, list) and len(p) >= 3]
        if len(coords) < 3:
            continue
        lons = [float(p[0]) for p in coords]
        lats = [float(p[1]) for p in coords]
        zs = [float(p[2]) for p in coords]
        if building not in roof_stats:
            roof_stats[building] = {
                "lon_sum": 0.0,
                "lat_sum": 0.0,
                "count": 0.0,
                "z_top": float(max(zs)),
            }
        roof_stats[building]["lon_sum"] += float(sum(lons))
        roof_stats[building]["lat_sum"] += float(sum(lats))
        roof_stats[building]["count"] += float(len(coords))
        roof_stats[building]["z_top"] = max(float(roof_stats[building]["z_top"]), float(max(zs)))

    max_solar_kwh = max([float(v) for v in solar_by_building_kwh.values()], default=0.0)
    low = (255, 204, 102)
    high = (226, 71, 23)
    bars: list[dict[str, Any]] = []
    for building, solar_kwh_raw in solar_by_building_kwh.items():
        solar_kwh = float(solar_kwh_raw)
        solar_mwh = solar_kwh / 1000.0
        if solar_mwh <= 0.0:
            continue

        if building in roof_stats and roof_stats[building]["count"] > 0:
            lon = roof_stats[building]["lon_sum"] / roof_stats[building]["count"]
            lat = roof_stats[building]["lat_sum"] / roof_stats[building]["count"]
            base_height_m = float(roof_stats[building]["z_top"]) + DEFAULT_BAR_BASE_OFFSET_M
        else:
            centroid = zone_centroids_wgs84.get(building)
            if centroid is None:
                continue
            lon = float(centroid[0])
            lat = float(centroid[1])
            base_height_m = DEFAULT_OSM_HEIGHT_M + DEFAULT_BAR_BASE_OFFSET_M

        bar_height_m = max(min_bar_height_m, solar_mwh * bar_scale_m_per_mwh)
        bars.append(
            {
                "building": building,
                "solar_kwh": solar_kwh,
                "solar_mwh": solar_mwh,
                "base_height_m": base_height_m,
                "bar_height_m": bar_height_m,
                "bar_width_m": float(bar_width_m),
                "source_position": [lon, lat, base_height_m],
                "target_position": [lon, lat, base_height_m + bar_height_m],
                "bar_colour": _map_colour(solar_kwh, max_solar_kwh, low, high),
            }
        )
    return bars


def render_html(
    output_path: str,
    payload: dict[str, Any],
) -> None:
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    html = f"""<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>Roof 3D Layer Visualiser</title>
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@400;500;600;700&family=IBM+Plex+Mono:wght@400;500&display=swap" rel="stylesheet">
  <script src="https://unpkg.com/deck.gl@latest/dist.min.js"></script>
  <script src="https://unpkg.com/maplibre-gl@latest/dist/maplibre-gl.js"></script>
  <link href="https://unpkg.com/maplibre-gl@latest/dist/maplibre-gl.css" rel="stylesheet" />
  <style>
    :root {{
      --bg-ink: #0f172a;
      --bg-slate: #111827;
      --panel-bg: rgba(12, 22, 36, 0.88);
      --panel-border: rgba(148, 163, 184, 0.24);
      --text-main: #e2e8f0;
      --text-soft: #94a3b8;
      --accent: #22d3ee;
      --accent-warm: #fb923c;
      --chip-bg: rgba(15, 23, 42, 0.65);
      --chip-border: rgba(34, 211, 238, 0.35);
    }}
    html, body {{
      margin: 0;
      width: 100%;
      height: 100%;
      overflow: hidden;
      font-family: "Space Grotesk", sans-serif;
      background:
        radial-gradient(1400px 900px at -20% -20%, #1e293b 0%, transparent 60%),
        radial-gradient(1300px 900px at 120% -30%, #164e63 0%, transparent 50%),
        linear-gradient(150deg, var(--bg-ink) 0%, var(--bg-slate) 100%);
      color: var(--text-main);
    }}
    #root {{
      display: grid;
      grid-template-columns: minmax(340px, 420px) 1fr;
      width: 100%;
      height: 100%;
    }}
    #sidebar {{
      background: var(--panel-bg);
      border-right: 1px solid var(--panel-border);
      backdrop-filter: blur(8px);
      padding: 16px 14px;
      box-sizing: border-box;
      overflow: auto;
    }}
    #map {{
      width: 100%;
      height: 100%;
      position: relative;
    }}
    .hero {{
      margin-bottom: 12px;
      padding-bottom: 10px;
      border-bottom: 1px solid rgba(148, 163, 184, 0.2);
    }}
    h1 {{
      margin: 0;
      font-size: 22px;
      letter-spacing: 0.3px;
      font-weight: 700;
      color: #f8fafc;
    }}
    .subtitle {{
      margin: 8px 0 0;
      font-size: 13px;
      line-height: 1.35;
      color: var(--text-soft);
    }}
    .meta-grid {{
      display: grid;
      grid-template-columns: 1fr 1fr;
      gap: 8px;
      margin-bottom: 12px;
    }}
    .metric-card {{
      border: 1px solid var(--chip-border);
      background: var(--chip-bg);
      border-radius: 10px;
      padding: 8px;
      min-height: 56px;
      display: grid;
      gap: 4px;
      align-content: start;
    }}
    .metric-label {{
      font-size: 11px;
      color: #67e8f9;
      text-transform: uppercase;
      letter-spacing: 0.65px;
    }}
    .metric-value {{
      font-size: 12px;
      line-height: 1.35;
      font-weight: 600;
      color: #e2e8f0;
      word-break: break-word;
    }}
    .panel {{
      border: 1px solid var(--panel-border);
      border-radius: 12px;
      padding: 10px 12px;
      margin-bottom: 10px;
      background: rgba(15, 23, 42, 0.58);
      box-shadow: 0 12px 24px rgba(2, 6, 23, 0.28);
    }}
    .panel h2 {{
      margin: 0 0 8px;
      font-size: 14px;
      font-weight: 600;
      color: #f8fafc;
    }}
    .layer-row {{
      display: grid;
      grid-template-columns: auto 1fr;
      align-items: center;
      column-gap: 8px;
      margin-bottom: 7px;
      font-size: 13px;
      border: 1px solid rgba(100, 116, 139, 0.22);
      border-radius: 9px;
      background: rgba(30, 41, 59, 0.45);
      padding: 8px;
      transition: border-color 140ms ease, background 140ms ease;
    }}
    .layer-row:hover {{
      border-color: rgba(34, 211, 238, 0.45);
      background: rgba(8, 47, 73, 0.45);
    }}
    .layer-row input {{
      width: 15px;
      height: 15px;
      accent-color: #22d3ee;
      margin-top: 1px;
    }}
    .hint {{
      font-size: 12px;
      color: var(--text-soft);
    }}
    .source-text {{
      display: block;
      margin-top: 2px;
      color: #cbd5e1;
      font-family: "IBM Plex Mono", monospace;
      font-size: 11px;
      line-height: 1.4;
      word-break: break-word;
    }}
    #details {{
      min-height: 100px;
      white-space: pre-line;
      font-size: 12px;
      line-height: 1.45;
      color: #f1f5f9;
      font-family: "IBM Plex Mono", monospace;
      background: rgba(2, 6, 23, 0.6);
      border: 1px solid rgba(148, 163, 184, 0.25);
      border-radius: 8px;
      padding: 10px;
      box-sizing: border-box;
    }}
    @media (max-width: 980px) {{
      #root {{
        grid-template-columns: 1fr;
        grid-template-rows: minmax(340px, 50vh) auto;
      }}
      #map {{
        grid-row: 1;
      }}
      #sidebar {{
        grid-row: 2;
        border-right: 0;
        border-top: 1px solid var(--panel-border);
      }}
      .meta-grid {{
        grid-template-columns: 1fr;
      }}
    }}
  </style>
</head>
<body>
  <div id="root">
    <aside id="sidebar">
      <div class="hero">
        <h1>Urban Roof Atlas</h1>
        <p class="subtitle">Interactive 3D inspection map for OSM context, roof geometry, and solar potential.</p>
      </div>
      <div class="meta-grid">
        <div class="metric-card">
          <span class="metric-label">Scenario</span>
          <span class="metric-value" id="scenarioPath"></span>
        </div>
        <div class="metric-card">
          <span class="metric-label">PV Panel</span>
          <span class="metric-value" id="pvPanel"></span>
        </div>
        <div class="metric-card">
          <span class="metric-label">OSM Buildings</span>
          <span class="metric-value" id="osmCount"></span>
        </div>
        <div class="metric-card">
          <span class="metric-label">Generated Roofs</span>
          <span class="metric-value" id="roofCount"></span>
        </div>
        <div class="metric-card">
          <span class="metric-label">Solar Bars</span>
          <span class="metric-value" id="barCount"></span>
        </div>
      </div>
      <div class="panel">
        <h2>Layers</h2>
        <label class="layer-row">
          <input id="toggleLayer1" type="checkbox" checked />
          <span>1. OpenStreetMap footprints (selected zone)</span>
        </label>
        <label class="layer-row">
          <input id="toggleLayer2" type="checkbox" checked />
          <span>2. Satellite image (fixedbox v3 output)</span>
        </label>
        <label class="layer-row">
          <input id="toggleLayer3" type="checkbox" checked />
          <span>3. OSM 3D + generated roofs</span>
        </label>
        <label class="layer-row">
          <input id="toggleLayer4" type="checkbox" />
          <span>4. OSM 3D buildings only (before roofs)</span>
        </label>
        <label class="layer-row">
          <input id="toggleLayer5" type="checkbox" checked />
          <span>5. Solar capacity bars</span>
        </label>
      </div>
      <div class="panel">
        <h2>Clicked Feature</h2>
        <div id="details">Click a building or roof to inspect details.</div>
      </div>
      <div class="panel">
        <h2>Data Sources</h2>
        <div class="hint">
          Satellite image source
          <span class="source-text" id="satPath"></span>
        </div>
        <div class="hint" style="margin-top:8px;">
          Roof file source
          <span class="source-text" id="roofPath"></span>
        </div>
        <div class="hint" style="margin-top:8px;">
          PV totals source
          <span class="source-text" id="pvPath"></span>
        </div>
      </div>
    </aside>
    <main id="map"></main>
  </div>
  <script>
    const payload = {json.dumps(payload, ensure_ascii=True)};
    const detailsEl = document.getElementById("details");
    const layerState = {{
      layer1: true,
      layer2: true,
      layer3: true,
      layer4: false,
      layer5: true
    }};
    document.getElementById("scenarioPath").textContent = payload.scenario;
    document.getElementById("pvPanel").textContent = payload.pv_panel || "{DEFAULT_PV_PANEL}";
    document.getElementById("osmCount").textContent = String((payload.osm_geojson.features || []).length);
    document.getElementById("roofCount").textContent = String((payload.roofs || []).length);
    document.getElementById("barCount").textContent = String((payload.bars || []).length);
    document.getElementById("satPath").textContent = payload.satellite_path || "(not found)";
    document.getElementById("roofPath").textContent = payload.roof_file_path || "(none)";
    document.getElementById("pvPath").textContent = payload.pv_source_path || "(not found)";

    function n(value, digits = 2) {{
      if (value === null || value === undefined || Number.isNaN(value)) return "-";
      return Number(value).toLocaleString(undefined, {{maximumFractionDigits: digits}});
    }}

    function tooltipBox(text) {{
      return {{
        text,
        style: {{
          backgroundColor: "rgba(15, 23, 42, 0.94)",
          color: "#e2e8f0",
          border: "1px solid rgba(148, 163, 184, 0.45)",
          borderRadius: "8px",
          fontFamily: "'IBM Plex Mono', monospace",
          fontSize: "12px",
          lineHeight: "1.4"
        }}
      }};
    }}

    function buildLayers() {{
      const layers = [];

      if (layerState.layer2 && payload.satellite_data_uri) {{
        const b = payload.satellite_bounds;
        layers.push(new deck.BitmapLayer({{
          id: "satellite-image",
          image: payload.satellite_data_uri,
          bounds: [[b.west, b.south], [b.west, b.north], [b.east, b.north], [b.east, b.south]],
          opacity: 0.9,
          desaturate: 0
        }}));
      }}

      if (layerState.layer1) {{
        layers.push(new deck.GeoJsonLayer({{
          id: "osm-zone-2d",
          data: payload.osm_geojson,
          pickable: true,
          stroked: true,
          filled: true,
          extruded: false,
          getFillColor: [51, 136, 255, 70],
          getLineColor: [26, 85, 204, 220],
          lineWidthMinPixels: 1.5
        }}));
      }}

      if (layerState.layer3) {{
        layers.push(new deck.GeoJsonLayer({{
          id: "osm-3d-with-roofs",
          data: payload.osm_geojson,
          pickable: true,
          stroked: true,
          filled: true,
          extruded: true,
          wireframe: true,
          opacity: 0.42,
          getFillColor: [100, 180, 255, 120],
          getLineColor: [255, 255, 255, 220],
          getElevation: f => Number((f.properties || {{}}).viz_height_m || 8)
        }}));

        layers.push(new deck.PolygonLayer({{
          id: "generated-roofs",
          data: payload.roofs || [],
          pickable: true,
          stroked: true,
          filled: true,
          extruded: false,
          getPolygon: d => d.polygon,
          getFillColor: d => d.fill_colour || [255, 140, 40, 220],
          getLineColor: [255, 255, 255, 190],
          lineWidthMinPixels: 1.2
        }}));
      }}

      if (layerState.layer4) {{
        layers.push(new deck.GeoJsonLayer({{
          id: "osm-3d-before-roofs",
          data: payload.osm_geojson,
          pickable: true,
          stroked: true,
          filled: true,
          extruded: true,
          wireframe: true,
          opacity: 0.38,
          getFillColor: [170, 180, 200, 120],
          getLineColor: [230, 236, 245, 210],
          getElevation: f => Number((f.properties || {{}}).viz_height_m || 8)
        }}));
      }}

      if (layerState.layer5) {{
        layers.push(new deck.LineLayer({{
          id: "solar-bars",
          data: payload.bars || [],
          pickable: true,
          widthUnits: "meters",
          getWidth: d => Number(d.bar_width_m || {DEFAULT_BAR_WIDTH_M}),
          getSourcePosition: d => d.source_position,
          getTargetPosition: d => d.target_position,
          getColor: d => [...(d.bar_colour || [255, 140, 40]), 230]
        }}));
      }}

      return layers;
    }}

    const deckgl = new deck.DeckGL({{
      container: document.getElementById("map"),
      mapStyle: payload.map_style,
      initialViewState: {{
        latitude: payload.centre_lat,
        longitude: payload.centre_lon,
        zoom: 17,
        pitch: 58,
        bearing: -12
      }},
      controller: true,
      layers: buildLayers(),
      getTooltip: info => {{
        if (!info || !info.object) return null;
        if (info.layer && info.layer.id === "generated-roofs") {{
          return tooltipBox(
            `Generated roof\\n` +
            `Building: ${{info.object.building || "-"}}\\n` +
            `Roof id: ${{info.object.roof_id || "-"}}\\n` +
            `Z range: ${{n(info.object.z_min, 2)}} - ${{n(info.object.z_max, 2)}} m`
          );
        }}
        if (
          info.layer &&
          (
            info.layer.id === "osm-zone-2d" ||
            info.layer.id === "osm-3d-with-roofs" ||
            info.layer.id === "osm-3d-before-roofs"
          )
        ) {{
          const p = info.object.properties || {{}};
          return tooltipBox(
            `OSM building\\n` +
            `OSM id: ${{p.osm_id || "-"}}\\n` +
            `Height: ${{n(p.viz_height_m, 2)}} m`
          );
        }}
        if (info.layer && info.layer.id === "solar-bars") {{
          return tooltipBox(
            `Solar capacity bar\\n` +
            `Building: ${{info.object.building || "-"}}\\n` +
            `Solar: ${{n(info.object.solar_kwh, 1)}} kWh/year\\n` +
            `Bar height: ${{n(info.object.bar_height_m, 2)}} m`
          );
        }}
        return null;
      }},
      onClick: info => {{
        if (!info || !info.object) return;
        if (info.layer && info.layer.id === "generated-roofs") {{
          const d = info.object;
          detailsEl.textContent =
            `Generated roof\\n` +
            `Building: ${{d.building || "-"}}\\n` +
            `Roof id: ${{d.roof_id || "-"}}\\n` +
            `Z min: ${{n(d.z_min, 2)}} m\\n` +
            `Z max: ${{n(d.z_max, 2)}} m`;
          return;
        }}
        if (info.layer && info.layer.id === "solar-bars") {{
          const d = info.object;
          detailsEl.textContent =
            `Solar capacity bar\\n` +
            `Building: ${{d.building || "-"}}\\n` +
            `Solar: ${{n(d.solar_kwh, 2)}} kWh/year\\n` +
            `Solar: ${{n(d.solar_mwh, 2)}} MWh/year\\n` +
            `Base elevation: ${{n(d.base_height_m, 2)}} m\\n` +
            `Bar height: ${{n(d.bar_height_m, 2)}} m`;
          return;
        }}
        const p = info.object.properties || {{}};
        detailsEl.textContent =
          `OSM building\\n` +
          `OSM id: ${{p.osm_id || "-"}}\\n` +
          `3D extrusion: ${{n(p.viz_height_m, 2)}} m`;
      }}
    }});

    function bindToggle(id, key) {{
      const element = document.getElementById(id);
      if (!element) return;
      layerState[key] = Boolean(element.checked);
      element.addEventListener("change", event => {{
        layerState[key] = Boolean(event.target.checked);
        deckgl.setProps({{layers: buildLayers()}});
      }});
    }}

    bindToggle("toggleLayer1", "layer1");
    bindToggle("toggleLayer2", "layer2");
    bindToggle("toggleLayer3", "layer3");
    bindToggle("toggleLayer4", "layer4");
    bindToggle("toggleLayer5", "layer5");
  </script>
</body>
</html>
"""
    with open(output_path, "w", encoding="utf-8") as fp:
        fp.write(html)


def main() -> None:
    args = parse_args()
    if args.bar_scale_m_per_mwh <= 0:
        raise ValueError("--bar-scale-m-per-mwh must be greater than zero.")
    if args.min_bar_height_m < 0:
        raise ValueError("--min-bar-height-m must be non-negative.")
    if args.bar_width_m <= 0:
        raise ValueError("--bar-width-m must be greater than zero.")

    scenario = os.path.abspath(args.scenario)
    if not os.path.isdir(scenario):
        raise NotADirectoryError(f"Scenario folder does not exist: {scenario}")

    locator = InputLocator(scenario)
    site_polygon = _load_zone_site_polygon_wgs84(locator)
    west, south, east, north = _site_bounds(site_polygon)
    centre_lat, centre_lon = _site_centre(site_polygon)

    roof_file_path = resolve_roof_file_path(scenario, args.roof_file)
    roofs = _load_roof_surfaces(roof_file_path)

    cache_dir = os.path.join(os.path.abspath(os.path.dirname(__file__)), "cache", "osm")
    osm_geojson = _fetch_osm_buildings_for_site(site_polygon, cache_dir=cache_dir)
    osm_geojson = _apply_osm_heights(osm_geojson, roofs)

    max_z = max([roof["z_max"] for roof in roofs], default=12.0)
    roofs_payload = []
    for roof in roofs:
        roofs_payload.append(
            {
                "building": roof.get("building", ""),
                "roof_id": roof.get("roof_id", ""),
                "polygon": roof.get("polygon", []),
                "z_min": float(roof.get("z_min", 0.0)),
                "z_max": float(roof.get("z_max", 0.0)),
                "fill_colour": [255, 165, 70, 220] if max_z <= 0 else [
                    int(220 + 35 * (roof.get("z_max", 0.0) / max_z)),
                    int(90 + 70 * (roof.get("z_max", 0.0) / max_z)),
                    40,
                    220,
                ],
            }
        )

    satellite_path = resolve_satellite_image_path(scenario, args.satellite_image)
    satellite_path = _ensure_matching_satellite_image(
        scenario=scenario,
        requested_satellite_path=satellite_path,
        roof_file_path=roof_file_path,
        site_bounds_wgs84=(west, south, east, north),
    )
    satellite_data_uri = _image_file_to_data_uri(satellite_path)
    if not satellite_data_uri:
        print(f"[warn] Satellite image not found at: {satellite_path}")

    solar_by_building, pv_source_path = _load_solar_capacity_by_building(locator, args.pv_panel)
    if not solar_by_building:
        print(f"[warn] No PV totals found for panel '{args.pv_panel}'. Solar bars will be empty.")
    zone_centroids_wgs84 = _load_zone_centroids_wgs84(locator)
    bars_payload = _build_solar_bars_payload(
        roofs_payload=roofs_payload,
        solar_by_building_kwh=solar_by_building,
        zone_centroids_wgs84=zone_centroids_wgs84,
        bar_scale_m_per_mwh=float(args.bar_scale_m_per_mwh),
        min_bar_height_m=float(args.min_bar_height_m),
        bar_width_m=float(args.bar_width_m),
    )

    payload = {
        "scenario": scenario,
        "pv_panel": str(args.pv_panel),
        "map_style": args.map_style,
        "osm_geojson": osm_geojson,
        "roofs": roofs_payload,
        "bars": bars_payload,
        "centre_lat": centre_lat,
        "centre_lon": centre_lon,
        "satellite_data_uri": satellite_data_uri,
        "satellite_path": satellite_path if os.path.exists(satellite_path) else "",
        "roof_file_path": roof_file_path,
        "pv_source_path": pv_source_path,
        "satellite_bounds": {
            "west": west,
            "south": south,
            "east": east,
            "north": north,
        },
    }

    output_path = resolve_output_html_path(scenario, args.output_html)
    render_html(output_path=output_path, payload=payload)

    print("[ok] Layered 3D roof visualiser generated.")
    print(f"Scenario: {scenario}")
    print(f"OSM buildings loaded: {len(osm_geojson.get('features', []))}")
    print(f"Generated roofs loaded: {len(roofs_payload)}")
    print(f"Solar bars loaded: {len(bars_payload)}")
    print(f"Output HTML: {output_path}")


if __name__ == "__main__":
    main()
