"""
Generate workflow comparison metrics for roof PV outputs.

This utility compares workflow snapshots generated by ``workflow_comparison.py``:
- workflow0_normal_flat_roofs (WF0)
- workflow1_geometry_generator (WF1)

It can report:
- scenario totals (default)
- building-level diagnostics
- both
"""

from __future__ import annotations

import argparse
import csv
import glob
import math
import os
import time
from typing import Any, Iterable


WORKFLOW_FOLDERS = {
    "WF0": "workflow0_normal_flat_roofs",
    "WF1": "workflow1_geometry_generator",
}
WORKFLOW_IDS = sorted(WORKFLOW_FOLDERS.keys())

DELTA_PAIRS = {
    "delta_total": ("WF1", "WF0"),
}

PV_METRICS = [
    "E_PV_gen_kWh",
    "area_PV_m2",
    "specific_yield_kWh_m2",
    "radiation_kWh",
    "radiation_kWh_m2",
]

ROOF_METRICS = [
    "roof_area_m2",
    "panel_area_installed_m2",
    "aw_tilt_deg",
    "aw_surface_tilt_deg",
    "aw_surface_azimuth_deg",
    "aw_panel_tilt_deg_area",
    "aw_panel_tilt_deg_module",
    "aw_panel_azimuth_deg_module",
    "orientation_share_flat",
    "orientation_share_N",
    "orientation_share_E",
    "orientation_share_S",
    "orientation_share_W",
    "panel_orientation_share_flat",
    "panel_orientation_share_N",
    "panel_orientation_share_E",
    "panel_orientation_share_S",
    "panel_orientation_share_W",
    "shading_cv_aw",
    "shading_p90_p10_Whm2",
    "shading_cv_aw_detrended",
    "shading_p90_p10_ratio_detrended",
]

ALL_METRICS = PV_METRICS + ROOF_METRICS

DEFAULT_FLAT_PANEL_AZIMUTH_DEG = 180.0
PANEL_AZIMUTH_OFFSET_DEG = 0.0
FLAT_SURFACE_TILT_TOL_DEG = 1e-3


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Create scenario/building metrics and WF deltas for roof-workflow-comparison outputs."
    )
    parser.add_argument(
        "--comparison-root",
        required=True,
        help="Path to outputs/data/roof-workflow-comparison.",
    )
    parser.add_argument(
        "--workflows",
        default="WF0,WF1",
        help="Comma-separated workflow ids to process (WF0, WF1). Default: WF0,WF1.",
    )
    parser.add_argument(
        "--workflow0-root",
        default="",
        help="Optional workflow root override for WF0.",
    )
    parser.add_argument(
        "--workflow1-root",
        default="",
        help="Optional workflow root override for WF1.",
    )
    parser.add_argument(
        "--level",
        default="scenario",
        choices=["scenario", "building", "both"],
        help="Output level to generate.",
    )
    parser.add_argument(
        "--buildings",
        default="",
        help="Optional comma-separated building filter (e.g. B1000,B1001).",
    )
    parser.add_argument(
        "--pv-panels",
        default="PV1",
        help="Comma-separated PV panel ids, with or without PV_ prefix.",
    )
    parser.add_argument(
        "--out-dir",
        default="",
        help="Output folder. Default: --comparison-root.",
    )
    parser.add_argument(
        "--approx-panel-area-m2",
        default=1.8,
        type=float,
        help="Approximate module area for panel count estimation (count = area_installed_module_m2 / this value).",
    )
    parser.add_argument(
        "--undo-pv-azimuth-harmonisation",
        action="store_true",
        help=(
            "Rotate non-flat panel azimuth bins by +180° to undo temporary PV azimuth harmonisation applied "
            "before PV runs in workflow comparison."
        ),
    )
    return parser.parse_args()


def to_float(value: str | None) -> float | None:
    if value is None:
        return None
    text = str(value).strip()
    if not text:
        return None
    try:
        return float(text)
    except ValueError:
        return None


def normalise_panel_ids(panel_arg: str) -> list[str]:
    panels: list[str] = []
    for token in panel_arg.split(","):
        raw = token.strip()
        if not raw:
            continue
        upper = raw.upper()
        if upper.startswith("PV_"):
            panel = upper
        elif upper.startswith("PV"):
            panel = f"PV_{upper}"
        else:
            panel = f"PV_{upper}"
        if panel not in panels:
            panels.append(panel)
    if not panels:
        raise ValueError("No valid panels parsed from --pv-panels.")
    return panels


def parse_building_filter(buildings_arg: str) -> set[str] | None:
    building_tokens = [token.strip() for token in buildings_arg.split(",") if token.strip()]
    if not building_tokens:
        return None
    return set(building_tokens)


def parse_workflow_ids(workflows_arg: str) -> list[str]:
    workflow_ids: list[str] = []
    for token in workflows_arg.split(","):
        workflow_id = token.strip().upper()
        if not workflow_id:
            continue
        if workflow_id not in WORKFLOW_FOLDERS:
            raise ValueError(
                f"Unsupported workflow id '{workflow_id}' in --workflows. "
                f"Allowed values: {', '.join(WORKFLOW_IDS)}."
            )
        if workflow_id not in workflow_ids:
            workflow_ids.append(workflow_id)
    if not workflow_ids:
        raise ValueError("No valid workflow ids parsed from --workflows.")
    return workflow_ids


def should_write_deltas(workflow_ids: list[str]) -> bool:
    return "WF0" in workflow_ids and "WF1" in workflow_ids


def resolve_workflow_root(
    workflow_id: str,
    comparison_root: str,
    workflow0_root_override: str,
    workflow1_root_override: str,
) -> str:
    if workflow_id == "WF0" and workflow0_root_override.strip():
        return os.path.abspath(workflow0_root_override.strip())
    if workflow_id == "WF1" and workflow1_root_override.strip():
        return os.path.abspath(workflow1_root_override.strip())
    return os.path.join(comparison_root, WORKFLOW_FOLDERS[workflow_id])


def iter_csv_rows(path: str) -> Iterable[list[str]]:
    with open(path, newline="", encoding="utf-8") as fp:
        reader = csv.reader(fp)
        for row in reader:
            yield row


def read_building_totals(path: str) -> dict[str, dict[str, float]]:
    if not os.path.exists(path):
        return {}
    out: dict[str, dict[str, float]] = {}
    with open(path, newline="", encoding="utf-8") as fp:
        reader = csv.DictReader(fp)
        for row in reader:
            building = (row.get("name") or "").strip()
            if not building:
                continue
            energy = to_float(row.get("E_PV_gen_kWh"))
            area = to_float(row.get("area_PV_m2"))
            radiation = to_float(row.get("radiation_kWh"))
            specific_yield = None if not area or area <= 0 else energy / area if energy is not None else None
            radiation_per_m2 = None if not area or area <= 0 else radiation / area if radiation is not None else None
            out[building] = {
                "E_PV_gen_kWh": energy,
                "area_PV_m2": area,
                "specific_yield_kWh_m2": specific_yield,
                "radiation_kWh": radiation,
                "radiation_kWh_m2": radiation_per_m2,
            }
    return out


def load_building_heights(workflow_root: str) -> dict[str, float]:
    """
    Estimate building height from workflow geometry metadata.

    Height is computed as:
    - max roof sensor Z minus min underside sensor Z, when both are available
    - otherwise max roof sensor Z minus terrain elevation, when available
    """
    solar_root = os.path.join(workflow_root, "solar-radiation")
    if not os.path.isdir(solar_root):
        return {}

    heights: dict[str, float] = {}
    for path in glob.glob(os.path.join(solar_root, "*_geometry.csv")):
        filename = os.path.basename(path)
        if not filename.endswith("_geometry.csv"):
            continue
        building = filename.replace("_geometry.csv", "")
        rows_iter = iter_csv_rows(path)
        try:
            header = next(rows_iter)
        except StopIteration:
            continue

        def idx(name: str) -> int:
            try:
                return header.index(name)
            except ValueError as exc:
                raise ValueError(f"Missing column '{name}' in {path}") from exc

        i_type = idx("TYPE")
        i_z = idx("Zcoor")
        i_terrain = idx("terrain_elevation")

        max_roof_z: float | None = None
        min_underside_z: float | None = None
        terrain_elevation: float | None = None

        for row in rows_iter:
            if len(row) <= max(i_type, i_z, i_terrain):
                continue
            type_name = row[i_type].strip().lower()
            z_value = to_float(row[i_z])
            terrain_value = to_float(row[i_terrain])

            if terrain_elevation is None and terrain_value is not None:
                terrain_elevation = terrain_value

            if z_value is None:
                continue

            if type_name == "roofs":
                max_roof_z = z_value if max_roof_z is None else max(max_roof_z, z_value)
            elif type_name == "undersides":
                min_underside_z = z_value if min_underside_z is None else min(min_underside_z, z_value)

        height: float | None = None
        if max_roof_z is not None and min_underside_z is not None:
            height = max_roof_z - min_underside_z
        elif max_roof_z is not None and terrain_elevation is not None:
            height = max_roof_z - terrain_elevation

        if height is not None and height >= 0:
            heights[building] = height

    return heights


def quadrant(azimuth_deg: float) -> str:
    az = azimuth_deg % 360.0
    if az < 45.0 or az >= 315.0:
        return "N"
    if az < 135.0:
        return "E"
    if az < 225.0:
        return "S"
    return "W"


def true_azimuth_from_normal(xdir: float, ydir: float) -> float:
    # xdir: east(+), west(-); ydir: north(+), south(-)
    # Result convention: 0=N, 90=E, 180=S, 270=W
    azimuth = math.degrees(math.atan2(xdir, ydir))
    if azimuth < 0:
        azimuth += 360.0
    return azimuth


def panel_azimuth_deg(
    xdir: float,
    ydir: float,
    panel_tilt_deg: float,
    surface_tilt_deg: float | None = None,
    surface_azimuth_deg: float | None = None,
    flat_panel_azimuth_deg: float = DEFAULT_FLAT_PANEL_AZIMUTH_DEG,
) -> float | None:
    if abs(panel_tilt_deg) <= 1e-6:
        return None
    # Flat roofs can carry tiny XY normal noise; treat them by convention (south-facing rows).
    # Keep this path independent from PANEL_AZIMUTH_OFFSET_DEG, which only undoes non-flat harmonisation.
    if surface_tilt_deg is not None and abs(surface_tilt_deg) <= FLAT_SURFACE_TILT_TOL_DEG:
        return flat_panel_azimuth_deg % 360.0
    # Prefer CEA azimuth column when available so report binning stays in CEA convention.
    if surface_azimuth_deg is not None:
        return (surface_azimuth_deg + PANEL_AZIMUTH_OFFSET_DEG) % 360.0
    # Fallback for legacy rows missing surface_azimuth_deg.
    if abs(xdir) > 1e-9 or abs(ydir) > 1e-9:
        return (true_azimuth_from_normal(xdir, ydir) + PANEL_AZIMUTH_OFFSET_DEG) % 360.0
    # Last fallback for degenerate rows.
    return flat_panel_azimuth_deg % 360.0


def surface_azimuth_deg_adjusted(
    xdir: float,
    ydir: float,
    surface_tilt_deg: float,
    surface_azimuth_deg: float | None = None,
) -> float | None:
    if abs(surface_tilt_deg) <= 1e-6:
        if surface_azimuth_deg is None:
            return None
        return surface_azimuth_deg % 360.0
    if surface_azimuth_deg is not None:
        return (surface_azimuth_deg + PANEL_AZIMUTH_OFFSET_DEG) % 360.0
    if abs(xdir) > 1e-9 or abs(ydir) > 1e-9:
        return (true_azimuth_from_normal(xdir, ydir) + PANEL_AZIMUTH_OFFSET_DEG) % 360.0
    return None


def weighted_quantile(values: list[float], weights: list[float], q: float) -> float:
    if not values:
        return float("nan")
    if len(values) != len(weights):
        raise ValueError("Values and weights length mismatch.")
    if q <= 0:
        return min(values)
    if q >= 1:
        return max(values)
    pairs = sorted(zip(values, weights), key=lambda vw: vw[0])
    total_weight = sum(w for _, w in pairs)
    if total_weight <= 0:
        return float("nan")
    threshold = q * total_weight
    cumulative = 0.0
    for value, weight in pairs:
        cumulative += weight
        if cumulative >= threshold:
            return value
    return pairs[-1][0]


def weighted_circular_mean_deg(values_deg: list[float], weights: list[float]) -> float | None:
    if not values_deg:
        return None
    if len(values_deg) != len(weights):
        raise ValueError("Values and weights length mismatch.")
    total_weight = sum(weights)
    if total_weight <= 0:
        return None

    sin_sum = 0.0
    cos_sum = 0.0
    for azimuth_deg, weight in zip(values_deg, weights):
        angle_rad = math.radians(azimuth_deg % 360.0)
        sin_sum += weight * math.sin(angle_rad)
        cos_sum += weight * math.cos(angle_rad)

    if abs(sin_sum) <= 1e-12 and abs(cos_sum) <= 1e-12:
        return None

    mean_deg = math.degrees(math.atan2(sin_sum, cos_sum))
    if mean_deg < 0:
        mean_deg += 360.0
    return mean_deg


def compute_detrended_shading_stats(roof_rows: list[dict[str, Any]]) -> tuple[float | None, float | None]:
    # Remove first-order geometry effects (tilt + orientation) before computing spread.
    # This keeps WF comparisons focused on shading heterogeneity, not different roof aspect mixes.
    bucket_weighted_radiation: dict[tuple[str, float], float] = {}
    bucket_weighted_area: dict[tuple[str, float], float] = {}

    for row in roof_rows:
        area = row["AREA_m2"]
        if area <= 0:
            continue
        panel_azimuth = panel_azimuth_deg(
            row["Xdir"],
            row["Ydir"],
            row["B_deg"],
            surface_tilt_deg=row["tilt_deg"],
            surface_azimuth_deg=row["surface_azimuth_deg"],
        )
        direction = "flat" if panel_azimuth is None else quadrant(panel_azimuth)
        tilt_bucket_deg = 0.0 if abs(row["B_deg"]) <= 1e-6 else round(row["B_deg"] / 5.0) * 5.0
        bucket = (direction, tilt_bucket_deg)
        bucket_weighted_radiation[bucket] = bucket_weighted_radiation.get(bucket, 0.0) + row["total_rad_Whm2"] * area
        bucket_weighted_area[bucket] = bucket_weighted_area.get(bucket, 0.0) + area

    bucket_mean_radiation = {
        bucket: bucket_weighted_radiation[bucket] / area
        for bucket, area in bucket_weighted_area.items()
        if area > 0
    }
    if not bucket_mean_radiation:
        return None, None

    detrended_values: list[float] = []
    detrended_weights: list[float] = []
    for row in roof_rows:
        area = row["AREA_m2"]
        if area <= 0:
            continue
        panel_azimuth = panel_azimuth_deg(
            row["Xdir"],
            row["Ydir"],
            row["B_deg"],
            surface_tilt_deg=row["tilt_deg"],
            surface_azimuth_deg=row["surface_azimuth_deg"],
        )
        direction = "flat" if panel_azimuth is None else quadrant(panel_azimuth)
        tilt_bucket_deg = 0.0 if abs(row["B_deg"]) <= 1e-6 else round(row["B_deg"] / 5.0) * 5.0
        bucket = (direction, tilt_bucket_deg)
        bucket_mean = bucket_mean_radiation.get(bucket)
        if bucket_mean is None or bucket_mean <= 0:
            continue
        detrended_values.append(row["total_rad_Whm2"] / bucket_mean)
        detrended_weights.append(area)

    if not detrended_values:
        return None, None

    total_weight = sum(detrended_weights)
    if total_weight <= 0:
        return None, None

    detrended_mean = sum(v * w for v, w in zip(detrended_values, detrended_weights)) / total_weight
    detrended_var = sum(((v - detrended_mean) ** 2) * w for v, w in zip(detrended_values, detrended_weights)) / total_weight
    detrended_cv = float("nan") if detrended_mean <= 0 else math.sqrt(detrended_var) / detrended_mean
    p10 = weighted_quantile(detrended_values, detrended_weights, 0.10)
    p90 = weighted_quantile(detrended_values, detrended_weights, 0.90)
    return detrended_cv, (p90 - p10)


def compute_sensor_stats(sensor_rows: list[dict[str, Any]]) -> dict[str, float] | None:
    if not sensor_rows:
        return None

    roof_rows = [row for row in sensor_rows if row["TYPE"] == "roofs" and row["AREA_m2"] > 0]
    if not roof_rows:
        return None

    roof_area = sum(row["AREA_m2"] for row in roof_rows)
    if roof_area <= 0:
        return None

    module_area = sum(row["area_installed_module_m2"] for row in roof_rows if row["area_installed_module_m2"] > 0)

    aw_surface_tilt = sum(row["tilt_deg"] * row["AREA_m2"] for row in roof_rows) / roof_area
    aw_panel_tilt_area = sum(row["B_deg"] * row["AREA_m2"] for row in roof_rows) / roof_area

    if module_area > 0:
        aw_panel_tilt_module = sum(row["B_deg"] * row["area_installed_module_m2"] for row in roof_rows) / module_area
    else:
        aw_panel_tilt_module = None

    orient_areas = {"flat": 0.0, "N": 0.0, "E": 0.0, "S": 0.0, "W": 0.0}
    panel_orient_areas = {"flat": 0.0, "N": 0.0, "E": 0.0, "S": 0.0, "W": 0.0}
    surface_azimuth_values_deg: list[float] = []
    surface_azimuth_weights_m2: list[float] = []
    panel_azimuth_values_deg: list[float] = []
    panel_azimuth_weights_m2: list[float] = []
    radiation_values: list[float] = []
    radiation_weights: list[float] = []
    for row in roof_rows:
        area = row["AREA_m2"]
        module = max(0.0, row["area_installed_module_m2"])

        surface_tilt = row["tilt_deg"]
        if abs(surface_tilt) <= 1e-6:
            orient_areas["flat"] += area
        else:
            surface_azimuth = surface_azimuth_deg_adjusted(
                row["Xdir"],
                row["Ydir"],
                surface_tilt,
                row["surface_azimuth_deg"],
            )
            if surface_azimuth is None:
                continue
            orient_areas[quadrant(surface_azimuth)] += area
            surface_azimuth_values_deg.append(surface_azimuth)
            surface_azimuth_weights_m2.append(area)

        panel_tilt = row["B_deg"]
        if abs(panel_tilt) <= 1e-6:
            panel_orient_areas["flat"] += module
        else:
            panel_azimuth = panel_azimuth_deg(
                row["Xdir"],
                row["Ydir"],
                panel_tilt,
                surface_tilt_deg=row["tilt_deg"],
                surface_azimuth_deg=row["surface_azimuth_deg"],
            )
            if panel_azimuth is None:
                panel_orient_areas["flat"] += module
            else:
                panel_orient_areas[quadrant(panel_azimuth)] += module
                if module > 0:
                    panel_azimuth_values_deg.append(panel_azimuth)
                    panel_azimuth_weights_m2.append(module)

        radiation_values.append(row["total_rad_Whm2"])
        radiation_weights.append(area)

    rad_mean = sum(v * w for v, w in zip(radiation_values, radiation_weights)) / roof_area
    rad_var = sum(((v - rad_mean) ** 2) * w for v, w in zip(radiation_values, radiation_weights)) / roof_area
    shading_cv = float("nan") if rad_mean <= 0 else math.sqrt(rad_var) / rad_mean
    p10 = weighted_quantile(radiation_values, radiation_weights, 0.10)
    p90 = weighted_quantile(radiation_values, radiation_weights, 0.90)
    shading_cv_detrended, shading_ratio_spread_detrended = compute_detrended_shading_stats(roof_rows)
    aw_surface_azimuth_deg = weighted_circular_mean_deg(surface_azimuth_values_deg, surface_azimuth_weights_m2)
    aw_panel_azimuth_deg_module = weighted_circular_mean_deg(panel_azimuth_values_deg, panel_azimuth_weights_m2)

    return {
        "roof_area_m2": roof_area,
        "panel_area_installed_m2": module_area,
        # Backwards-compatible alias
        "aw_tilt_deg": aw_surface_tilt,
        # Explicit surface vs panel tilt metrics
        "aw_surface_tilt_deg": aw_surface_tilt,
        "aw_surface_azimuth_deg": aw_surface_azimuth_deg,
        "aw_panel_tilt_deg_area": aw_panel_tilt_area,
        "aw_panel_tilt_deg_module": aw_panel_tilt_module,
        "aw_panel_azimuth_deg_module": aw_panel_azimuth_deg_module,
        "orientation_area_flat_m2": orient_areas["flat"],
        "orientation_area_N_m2": orient_areas["N"],
        "orientation_area_E_m2": orient_areas["E"],
        "orientation_area_S_m2": orient_areas["S"],
        "orientation_area_W_m2": orient_areas["W"],
        "orientation_share_flat": orient_areas["flat"] / roof_area,
        "orientation_share_N": orient_areas["N"] / roof_area,
        "orientation_share_E": orient_areas["E"] / roof_area,
        "orientation_share_S": orient_areas["S"] / roof_area,
        "orientation_share_W": orient_areas["W"] / roof_area,
        "panel_orientation_share_flat": None if module_area <= 0 else panel_orient_areas["flat"] / module_area,
        "panel_orientation_share_N": None if module_area <= 0 else panel_orient_areas["N"] / module_area,
        "panel_orientation_share_E": None if module_area <= 0 else panel_orient_areas["E"] / module_area,
        "panel_orientation_share_S": None if module_area <= 0 else panel_orient_areas["S"] / module_area,
        "panel_orientation_share_W": None if module_area <= 0 else panel_orient_areas["W"] / module_area,
        "shading_cv_aw": shading_cv,
        "shading_p90_p10_Whm2": p90 - p10,
        "shading_cv_aw_detrended": shading_cv_detrended,
        "shading_p90_p10_ratio_detrended": shading_ratio_spread_detrended,
    }


def load_sensor_stats(workflow_root: str) -> tuple[dict[str, dict[str, float]], dict[str, list[dict[str, Any]]]]:
    sensors_root = os.path.join(workflow_root, "potentials", "solar", "sensors")
    per_building: dict[str, dict[str, float]] = {}
    raw_rows: dict[str, list[dict[str, Any]]] = {}

    if not os.path.isdir(sensors_root):
        return per_building, raw_rows

    for path in glob.glob(os.path.join(sensors_root, "*_PV_sensors.csv")):
        filename = os.path.basename(path)
        building = filename.replace("_PV_sensors.csv", "")
        rows_iter = iter_csv_rows(path)
        try:
            header = next(rows_iter)
        except StopIteration:
            continue

        def idx(name: str) -> int:
            try:
                return header.index(name)
            except ValueError as exc:
                raise ValueError(f"Missing column '{name}' in {path}") from exc

        i_type = idx("TYPE")
        i_area = idx("AREA_m2")
        i_tilt = idx("tilt_deg")
        i_panel_tilt = idx("B_deg")
        i_az = idx("surface_azimuth_deg")
        i_rad = idx("total_rad_Whm2")
        i_module = idx("area_installed_module_m2")
        i_xdir = idx("Xdir")
        i_ydir = idx("Ydir")

        rows: list[dict[str, Any]] = []
        for row in rows_iter:
            if len(row) <= max(i_type, i_area, i_tilt, i_panel_tilt, i_az, i_rad, i_module, i_xdir, i_ydir):
                continue
            type_name = row[i_type].strip()
            area = to_float(row[i_area])
            tilt = to_float(row[i_tilt])
            panel_tilt = to_float(row[i_panel_tilt])
            azimuth = to_float(row[i_az])
            radiation = to_float(row[i_rad])
            module_area = to_float(row[i_module])
            xdir = to_float(row[i_xdir])
            ydir = to_float(row[i_ydir])
            if (
                area is None
                or tilt is None
                or panel_tilt is None
                or azimuth is None
                or radiation is None
                or xdir is None
                or ydir is None
            ):
                continue
            rows.append(
                {
                    "TYPE": type_name,
                    "AREA_m2": area,
                    "tilt_deg": tilt,
                    "B_deg": panel_tilt,
                    "surface_azimuth_deg": azimuth,
                    "total_rad_Whm2": radiation,
                    "area_installed_module_m2": 0.0 if module_area is None else module_area,
                    "Xdir": xdir,
                    "Ydir": ydir,
                }
            )
        raw_rows[building] = rows
        stats = compute_sensor_stats(rows)
        if stats is not None:
            per_building[building] = stats

    return per_building, raw_rows


def parse_numeric_row(
    key_fields: dict[str, Any],
    pv_metrics: dict[str, float] | None,
    sensor_metrics: dict[str, float] | None,
    building_height_m: float | None = None,
) -> dict[str, Any]:
    row = dict(key_fields)
    row["pv_data_available"] = pv_metrics is not None
    row["sensor_data_available"] = sensor_metrics is not None
    row["building_height_m"] = building_height_m
    if not pv_metrics and not sensor_metrics:
        row["missing_status"] = "missing_pv_and_sensors"
    elif not pv_metrics:
        row["missing_status"] = "missing_pv"
    elif not sensor_metrics:
        row["missing_status"] = "missing_sensors"
    else:
        row["missing_status"] = "ok"

    for metric in PV_METRICS:
        row[metric] = None if pv_metrics is None else pv_metrics.get(metric)
    for metric in ROOF_METRICS:
        row[metric] = None if sensor_metrics is None else sensor_metrics.get(metric)
    return row


def aggregate_scenario_rows(building_rows: list[dict[str, Any]]) -> list[dict[str, Any]]:
    grouped: dict[tuple[str, str], list[dict[str, Any]]] = {}
    for row in building_rows:
        key = (row["workflow_id"], row["pv_panel"])
        grouped.setdefault(key, []).append(row)

    scenario_rows: list[dict[str, Any]] = []
    for (workflow_id, pv_panel), rows in sorted(grouped.items()):
        workflow_name = rows[0]["workflow_name"]

        pv_valid = [r for r in rows if r["pv_data_available"]]
        sensor_valid = [r for r in rows if r["sensor_data_available"]]

        e_sum = sum(r["E_PV_gen_kWh"] for r in pv_valid if r["E_PV_gen_kWh"] is not None)
        area_sum = sum(r["area_PV_m2"] for r in pv_valid if r["area_PV_m2"] is not None)
        rad_sum = sum(r["radiation_kWh"] for r in pv_valid if r["radiation_kWh"] is not None)
        specific_yield = None if area_sum <= 0 else e_sum / area_sum
        radiation_per_m2 = None if area_sum <= 0 else rad_sum / area_sum

        roof_area_sum = sum(r["roof_area_m2"] for r in sensor_valid if r["roof_area_m2"] is not None)
        panel_area_installed_sum = sum(
            r["panel_area_installed_m2"] for r in sensor_valid if r["panel_area_installed_m2"] is not None
        )
        if roof_area_sum > 0:
            aw_surface_tilt = (
                sum(
                    r["aw_surface_tilt_deg"] * r["roof_area_m2"]
                    for r in sensor_valid
                    if r["aw_surface_tilt_deg"] is not None
                )
                / roof_area_sum
            )
            aw_surface_azimuth_deg = weighted_circular_mean_deg(
                [r["aw_surface_azimuth_deg"] for r in sensor_valid if r["aw_surface_azimuth_deg"] is not None],
                [r["roof_area_m2"] for r in sensor_valid if r["aw_surface_azimuth_deg"] is not None and r["roof_area_m2"] is not None],
            )
            aw_panel_tilt_area = (
                sum(
                    r["aw_panel_tilt_deg_area"] * r["roof_area_m2"]
                    for r in sensor_valid
                    if r["aw_panel_tilt_deg_area"] is not None
                )
                / roof_area_sum
            )
            share_flat = (
                sum(
                    r["orientation_share_flat"] * r["roof_area_m2"]
                    for r in sensor_valid
                    if r["orientation_share_flat"] is not None
                )
                / roof_area_sum
            )
            share_n = (
                sum(
                    r["orientation_share_N"] * r["roof_area_m2"]
                    for r in sensor_valid
                    if r["orientation_share_N"] is not None
                )
                / roof_area_sum
            )
            share_e = (
                sum(
                    r["orientation_share_E"] * r["roof_area_m2"]
                    for r in sensor_valid
                    if r["orientation_share_E"] is not None
                )
                / roof_area_sum
            )
            share_s = (
                sum(
                    r["orientation_share_S"] * r["roof_area_m2"]
                    for r in sensor_valid
                    if r["orientation_share_S"] is not None
                )
                / roof_area_sum
            )
            share_w = (
                sum(
                    r["orientation_share_W"] * r["roof_area_m2"]
                    for r in sensor_valid
                    if r["orientation_share_W"] is not None
                )
                / roof_area_sum
            )

            shading_cv = (
                sum(r["shading_cv_aw"] * r["roof_area_m2"] for r in sensor_valid if r["shading_cv_aw"] is not None)
                / roof_area_sum
            )
            shading_spread = (
                sum(
                    r["shading_p90_p10_Whm2"] * r["roof_area_m2"]
                    for r in sensor_valid
                    if r["shading_p90_p10_Whm2"] is not None
                )
                / roof_area_sum
            )
            shading_cv_detrended = (
                sum(
                    r["shading_cv_aw_detrended"] * r["roof_area_m2"]
                    for r in sensor_valid
                    if r["shading_cv_aw_detrended"] is not None
                )
                / roof_area_sum
            )
            shading_ratio_spread_detrended = (
                sum(
                    r["shading_p90_p10_ratio_detrended"] * r["roof_area_m2"]
                    for r in sensor_valid
                    if r["shading_p90_p10_ratio_detrended"] is not None
                )
                / roof_area_sum
            )
        else:
            aw_surface_tilt = None
            aw_surface_azimuth_deg = None
            aw_panel_tilt_area = None
            share_flat = None
            share_n = None
            share_e = None
            share_s = None
            share_w = None
            shading_cv = None
            shading_spread = None
            shading_cv_detrended = None
            shading_ratio_spread_detrended = None

        if panel_area_installed_sum > 0:
            aw_panel_tilt_module = (
                sum(
                    r["aw_panel_tilt_deg_module"] * r["panel_area_installed_m2"]
                    for r in sensor_valid
                    if r["aw_panel_tilt_deg_module"] is not None and r["panel_area_installed_m2"] is not None
                )
                / panel_area_installed_sum
            )
            aw_panel_azimuth_deg_module = weighted_circular_mean_deg(
                [r["aw_panel_azimuth_deg_module"] for r in sensor_valid if r["aw_panel_azimuth_deg_module"] is not None],
                [
                    r["panel_area_installed_m2"]
                    for r in sensor_valid
                    if r["aw_panel_azimuth_deg_module"] is not None and r["panel_area_installed_m2"] is not None
                ],
            )
            panel_share_flat = (
                sum(
                    r["panel_orientation_share_flat"] * r["panel_area_installed_m2"]
                    for r in sensor_valid
                    if r["panel_orientation_share_flat"] is not None and r["panel_area_installed_m2"] is not None
                )
                / panel_area_installed_sum
            )
            panel_share_n = (
                sum(
                    r["panel_orientation_share_N"] * r["panel_area_installed_m2"]
                    for r in sensor_valid
                    if r["panel_orientation_share_N"] is not None and r["panel_area_installed_m2"] is not None
                )
                / panel_area_installed_sum
            )
            panel_share_e = (
                sum(
                    r["panel_orientation_share_E"] * r["panel_area_installed_m2"]
                    for r in sensor_valid
                    if r["panel_orientation_share_E"] is not None and r["panel_area_installed_m2"] is not None
                )
                / panel_area_installed_sum
            )
            panel_share_s = (
                sum(
                    r["panel_orientation_share_S"] * r["panel_area_installed_m2"]
                    for r in sensor_valid
                    if r["panel_orientation_share_S"] is not None and r["panel_area_installed_m2"] is not None
                )
                / panel_area_installed_sum
            )
            panel_share_w = (
                sum(
                    r["panel_orientation_share_W"] * r["panel_area_installed_m2"]
                    for r in sensor_valid
                    if r["panel_orientation_share_W"] is not None and r["panel_area_installed_m2"] is not None
                )
                / panel_area_installed_sum
            )
        else:
            aw_panel_tilt_module = None
            aw_panel_azimuth_deg_module = None
            panel_share_flat = None
            panel_share_n = None
            panel_share_e = None
            panel_share_s = None
            panel_share_w = None

        row = {
            "workflow_id": workflow_id,
            "workflow_name": workflow_name,
            "pv_panel": pv_panel,
            "building": "__SCENARIO__",
            "pv_data_available": bool(pv_valid),
            "sensor_data_available": bool(sensor_valid),
            "missing_status": "ok" if pv_valid and sensor_valid else "incomplete",
            "E_PV_gen_kWh": e_sum if pv_valid else None,
            "area_PV_m2": area_sum if pv_valid else None,
            "specific_yield_kWh_m2": specific_yield,
            "radiation_kWh": rad_sum if pv_valid else None,
            "radiation_kWh_m2": radiation_per_m2,
            "roof_area_m2": roof_area_sum if sensor_valid else None,
            "panel_area_installed_m2": panel_area_installed_sum if sensor_valid else None,
            "aw_tilt_deg": aw_surface_tilt,
            "aw_surface_tilt_deg": aw_surface_tilt,
            "aw_surface_azimuth_deg": aw_surface_azimuth_deg,
            "aw_panel_tilt_deg_area": aw_panel_tilt_area,
            "aw_panel_tilt_deg_module": aw_panel_tilt_module,
            "aw_panel_azimuth_deg_module": aw_panel_azimuth_deg_module,
            "orientation_share_flat": share_flat,
            "orientation_share_N": share_n,
            "orientation_share_E": share_e,
            "orientation_share_S": share_s,
            "orientation_share_W": share_w,
            "panel_orientation_share_flat": panel_share_flat,
            "panel_orientation_share_N": panel_share_n,
            "panel_orientation_share_E": panel_share_e,
            "panel_orientation_share_S": panel_share_s,
            "panel_orientation_share_W": panel_share_w,
            "shading_cv_aw": shading_cv,
            "shading_p90_p10_Whm2": shading_spread,
            "shading_cv_aw_detrended": shading_cv_detrended,
            "shading_p90_p10_ratio_detrended": shading_ratio_spread_detrended,
            "n_buildings_with_pv_data": len(pv_valid),
            "n_buildings_with_sensor_data": len(sensor_valid),
        }
        scenario_rows.append(row)

    return scenario_rows


def build_panel_placement_rows(
    workflow_data: dict[str, dict[str, Any]],
    panels: list[str],
    buildings: list[str],
    approx_panel_area_m2: float,
) -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    for workflow_id, wf_data in workflow_data.items():
        workflow_name = wf_data["workflow_name"]
        sensor_raw_rows_by_building: dict[str, list[dict[str, Any]]] = wf_data["sensor_raw_rows"]

        for building in buildings:
            roof_rows = [
                row
                for row in sensor_raw_rows_by_building.get(building, [])
                if row.get("TYPE") == "roofs" and row.get("area_installed_module_m2", 0.0) > 0
            ]
            if not roof_rows:
                for panel in panels:
                    rows.append(
                        {
                            "workflow_id": workflow_id,
                            "workflow_name": workflow_name,
                            "pv_panel": panel,
                            "building": building,
                            "direction": "",
                            "tilt_deg": None,
                            "panel_area_m2": None,
                            "panel_count_approx": None,
                            "share_of_panel_area": None,
                            "missing_status": "missing_sensor_rows",
                        }
                    )
                continue

            base_panel_area = sum(row["area_installed_module_m2"] for row in roof_rows)
            bins: dict[tuple[str, float], dict[str, float]] = {}
            for sensor in roof_rows:
                panel_tilt = sensor["B_deg"]
                true_azimuth = panel_azimuth_deg(
                    sensor["Xdir"],
                    sensor["Ydir"],
                    panel_tilt,
                    surface_tilt_deg=sensor["tilt_deg"],
                    surface_azimuth_deg=sensor["surface_azimuth_deg"],
                )
                direction = "flat" if true_azimuth is None else quadrant(true_azimuth)
                # Round for stable grouping and cleaner CSV output.
                bin_key = (direction, round(float(panel_tilt), 6))
                if bin_key not in bins:
                    bins[bin_key] = {"panel_area_m2": 0.0, "radiation_weight_Wh": 0.0}
                module_area = sensor["area_installed_module_m2"]
                bins[bin_key]["panel_area_m2"] += module_area
                # Proxy for directional energy split: annual irradiation per sensor * installed module area
                bins[bin_key]["radiation_weight_Wh"] += sensor["total_rad_Whm2"] * module_area

            for panel in panels:
                panel_totals = wf_data["panel_totals"][panel]
                panel_metrics = panel_totals.get(building)
                if panel_metrics is None or panel_metrics.get("area_PV_m2") is None:
                    rows.append(
                        {
                            "workflow_id": workflow_id,
                            "workflow_name": workflow_name,
                            "pv_panel": panel,
                            "building": building,
                            "direction": "",
                            "tilt_deg": None,
                            "panel_area_m2": None,
                            "panel_count_approx": None,
                            "share_of_panel_area": None,
                            "radiation_kWh_approx": None,
                            "share_of_radiation": None,
                            "E_PV_gen_kWh_approx": None,
                            "share_of_generation": None,
                            "missing_status": "missing_panel_totals",
                        }
                    )
                    continue

                target_panel_area = panel_metrics["area_PV_m2"]
                scale = 0.0 if base_panel_area <= 0 else target_panel_area / base_panel_area
                total_weight = sum(bin_data["radiation_weight_Wh"] for bin_data in bins.values())
                total_radiation = panel_metrics.get("radiation_kWh")
                total_generation = panel_metrics.get("E_PV_gen_kWh")

                for (direction, tilt_deg), bin_data in sorted(bins.items()):
                    panel_area = bin_data["panel_area_m2"] * scale
                    panel_count = None if approx_panel_area_m2 <= 0 else panel_area / approx_panel_area_m2
                    share = None if target_panel_area <= 0 else panel_area / target_panel_area
                    weight_share = None if total_weight <= 0 else bin_data["radiation_weight_Wh"] / total_weight
                    radiation_kwh_approx = None if total_radiation is None or weight_share is None else total_radiation * weight_share
                    generation_kwh_approx = None if total_generation is None or weight_share is None else total_generation * weight_share
                    rows.append(
                        {
                            "workflow_id": workflow_id,
                            "workflow_name": workflow_name,
                            "pv_panel": panel,
                            "building": building,
                            "direction": direction,
                            "tilt_deg": tilt_deg,
                            "panel_area_m2": panel_area,
                            "panel_count_approx": panel_count,
                            "share_of_panel_area": share,
                            "radiation_kWh_approx": radiation_kwh_approx,
                            "share_of_radiation": weight_share,
                            "E_PV_gen_kWh_approx": generation_kwh_approx,
                            "share_of_generation": weight_share,
                            "missing_status": "ok",
                        }
                    )
    return rows


def build_delta_rows(base_rows: list[dict[str, Any]], key_fields: list[str]) -> list[dict[str, Any]]:
    grouped: dict[tuple[Any, ...], dict[str, dict[str, Any]]] = {}
    for row in base_rows:
        key = tuple(row[field] for field in key_fields)
        grouped.setdefault(key, {})[row["workflow_id"]] = row

    out: list[dict[str, Any]] = []
    for key, wf_rows in sorted(grouped.items()):
        row: dict[str, Any] = {field: value for field, value in zip(key_fields, key)}
        for workflow_id in WORKFLOW_IDS:
            row[f"{workflow_id.lower()}_present"] = workflow_id in wf_rows
        if all(workflow_id in wf_rows for workflow_id in WORKFLOW_IDS):
            row["missing_status"] = "ok"
        else:
            missing = [workflow_id for workflow_id in WORKFLOW_IDS if workflow_id not in wf_rows]
            row["missing_status"] = f"missing_{'_'.join(w.lower() for w in missing)}"

        for metric in ALL_METRICS:
            values = {
                workflow_id: (wf_rows[workflow_id].get(metric) if workflow_id in wf_rows else None)
                for workflow_id in WORKFLOW_IDS
            }
            row[f"value_wf0_{metric}"] = values["WF0"]
            row[f"value_wf1_{metric}"] = values["WF1"]

            for delta_name, (lhs, rhs) in DELTA_PAIRS.items():
                lhs_val = values.get(lhs)
                rhs_val = values.get(rhs)
                row[f"{delta_name}_{metric}"] = None if lhs_val is None or rhs_val is None else lhs_val - rhs_val
        out.append(row)
    return out


def round_for_output(value: Any) -> Any:
    if isinstance(value, float):
        if math.isnan(value) or math.isinf(value):
            return ""
        return round(value, 6)
    if value is None:
        return ""
    return value


def write_csv(path: str, rows: list[dict[str, Any]], field_order: list[str]) -> str:
    os.makedirs(os.path.dirname(path), exist_ok=True)
    try:
        with open(path, "w", newline="", encoding="utf-8") as fp:
            writer = csv.DictWriter(fp, fieldnames=field_order, extrasaction="ignore")
            writer.writeheader()
            for row in rows:
                writer.writerow({field: round_for_output(row.get(field)) for field in field_order})
        return path
    except PermissionError:
        pass

    # Windows-friendly fallback when target CSV is open (e.g., in Excel):
    # write to a timestamped sibling file instead of failing the entire run.
    stem, ext = os.path.splitext(path)
    fallback_path = f"{stem}.locked_{int(time.time())}{ext}"
    try:
        with open(fallback_path, "w", newline="", encoding="utf-8") as fp:
            writer = csv.DictWriter(fp, fieldnames=field_order, extrasaction="ignore")
            writer.writeheader()
            for row in rows:
                writer.writerow({field: round_for_output(row.get(field)) for field in field_order})
        print(f"[warn] Could not overwrite locked file: {path}")
        print(f"[warn] Wrote metrics to fallback file instead: {fallback_path}")
        return fallback_path
    except PermissionError:
        pass

    # Final fallback: write into project-local tmp folder if output directory itself is not writable.
    basename = os.path.basename(path)
    local_tmp_dir = os.path.join(os.getcwd(), "tmp", "workflow_metrics_fallback")
    os.makedirs(local_tmp_dir, exist_ok=True)
    local_fallback_path = os.path.join(local_tmp_dir, f"{basename}.locked_{int(time.time())}")
    with open(local_fallback_path, "w", newline="", encoding="utf-8") as fp:
        writer = csv.DictWriter(fp, fieldnames=field_order, extrasaction="ignore")
        writer.writeheader()
        for row in rows:
            writer.writerow({field: round_for_output(row.get(field)) for field in field_order})
    print(f"[warn] Could not overwrite locked or non-writable file: {path}")
    print(f"[warn] Wrote metrics to local fallback file instead: {local_fallback_path}")
    return local_fallback_path


def build_field_order(rows: list[dict[str, Any]], preferred_first: list[str]) -> list[str]:
    keys = set()
    for row in rows:
        keys.update(row.keys())
    remaining = sorted(k for k in keys if k not in preferred_first)
    return [k for k in preferred_first if k in keys] + remaining


def main() -> None:
    global PANEL_AZIMUTH_OFFSET_DEG
    args = parse_args()
    PANEL_AZIMUTH_OFFSET_DEG = 180.0 if args.undo_pv_azimuth_harmonisation else 0.0
    comparison_root = os.path.abspath(args.comparison_root)
    if not os.path.isdir(comparison_root):
        raise NotADirectoryError(f"Comparison root does not exist: {comparison_root}")

    out_dir = os.path.abspath(args.out_dir) if args.out_dir else comparison_root
    panels = normalise_panel_ids(args.pv_panels)
    building_filter = parse_building_filter(args.buildings)
    selected_workflow_ids = parse_workflow_ids(args.workflows)
    write_deltas = should_write_deltas(selected_workflow_ids)

    workflow_data: dict[str, dict[str, Any]] = {}
    workflow_roots: dict[str, str] = {}
    for workflow_id in selected_workflow_ids:
        folder_name = WORKFLOW_FOLDERS[workflow_id]
        workflow_root = resolve_workflow_root(
            workflow_id=workflow_id,
            comparison_root=comparison_root,
            workflow0_root_override=args.workflow0_root,
            workflow1_root_override=args.workflow1_root,
        )
        workflow_roots[workflow_id] = workflow_root
        sensor_stats, raw_sensor_rows = load_sensor_stats(workflow_root)

        panel_totals: dict[str, dict[str, dict[str, float]]] = {}
        for panel in panels:
            filename = f"{panel}_total_buildings.csv"
            totals_path = os.path.join(workflow_root, "potentials", "solar", filename)
            panel_totals[panel] = read_building_totals(totals_path)

        workflow_data[workflow_id] = {
            "workflow_name": folder_name,
            "sensor_stats": sensor_stats,
            "sensor_raw_rows": raw_sensor_rows,
            "building_heights": load_building_heights(workflow_root),
            "panel_totals": panel_totals,
        }

    all_buildings: set[str] = set()
    for wf_data in workflow_data.values():
        all_buildings.update(wf_data["sensor_stats"].keys())
        for panel in panels:
            all_buildings.update(wf_data["panel_totals"][panel].keys())
    if building_filter is not None:
        all_buildings = {b for b in all_buildings if b in building_filter}

    building_rows: list[dict[str, Any]] = []
    for workflow_id, wf_data in workflow_data.items():
        workflow_name = wf_data["workflow_name"]
        sensor_stats = wf_data["sensor_stats"]
        building_heights = wf_data["building_heights"]
        for panel in panels:
            pv_totals = wf_data["panel_totals"][panel]
            for building in sorted(all_buildings):
                pv_metrics = pv_totals.get(building)
                roof_metrics = sensor_stats.get(building)
                key_fields = {
                    "workflow_id": workflow_id,
                    "workflow_name": workflow_name,
                    "pv_panel": panel,
                    "building": building,
                }
                building_rows.append(
                    parse_numeric_row(
                        key_fields,
                        pv_metrics,
                        roof_metrics,
                        building_height_m=building_heights.get(building),
                    )
                )

    scenario_rows = aggregate_scenario_rows(building_rows)
    scenario_delta_rows = build_delta_rows(scenario_rows, key_fields=["pv_panel"]) if write_deltas else []
    building_delta_rows = (
        build_delta_rows(building_rows, key_fields=["pv_panel", "building"]) if write_deltas else []
    )
    panel_placement_rows = build_panel_placement_rows(
        workflow_data=workflow_data,
        panels=panels,
        buildings=sorted(all_buildings),
        approx_panel_area_m2=args.approx_panel_area_m2,
    )

    outputs_written: list[str] = []
    if args.level in ("scenario", "both"):
        scenario_metrics_fields = build_field_order(
            scenario_rows,
            preferred_first=[
                "workflow_id",
                "workflow_name",
                "pv_panel",
                "pv_data_available",
                "sensor_data_available",
                "missing_status",
                "n_buildings_with_pv_data",
                "n_buildings_with_sensor_data",
            ],
        )
        path_metrics = os.path.join(out_dir, "scenario_metrics.csv")
        written_metrics = write_csv(path_metrics, scenario_rows, scenario_metrics_fields)
        outputs_written.append(written_metrics)
        if write_deltas:
            scenario_delta_fields = build_field_order(
                scenario_delta_rows,
                preferred_first=["pv_panel", "wf0_present", "wf1_present", "missing_status"],
            )
            path_deltas = os.path.join(out_dir, "scenario_deltas.csv")
            written_deltas = write_csv(path_deltas, scenario_delta_rows, scenario_delta_fields)
            outputs_written.append(written_deltas)

    if args.level in ("building", "both"):
        building_metrics_fields = build_field_order(
            building_rows,
            preferred_first=[
                "workflow_id",
                "workflow_name",
                "pv_panel",
                "building",
                "building_height_m",
                "pv_data_available",
                "sensor_data_available",
                "missing_status",
            ],
        )
        path_metrics = os.path.join(out_dir, "building_metrics.csv")
        written_metrics = write_csv(path_metrics, building_rows, building_metrics_fields)
        outputs_written.append(written_metrics)
        if write_deltas:
            building_delta_fields = build_field_order(
                building_delta_rows,
                preferred_first=["pv_panel", "building", "wf0_present", "wf1_present", "missing_status"],
            )
            path_deltas = os.path.join(out_dir, "building_deltas.csv")
            written_deltas = write_csv(path_deltas, building_delta_rows, building_delta_fields)
            outputs_written.append(written_deltas)

    if args.level in ("building", "both"):
        panel_placement_fields = [
            "workflow_id",
            "workflow_name",
            "pv_panel",
            "building",
            "direction",
            "tilt_deg",
            "panel_area_m2",
            "panel_count_approx",
            "share_of_panel_area",
            "radiation_kWh_approx",
            "share_of_radiation",
            "E_PV_gen_kWh_approx",
            "share_of_generation",
            "missing_status",
        ]
        path_panel_placement = os.path.join(out_dir, "panel_placement_summary.csv")
        written_panel_placement = write_csv(path_panel_placement, panel_placement_rows, panel_placement_fields)
        outputs_written.append(written_panel_placement)

    print("Workflow metrics report completed.")
    print(f"comparison_root: {comparison_root}")
    print(f"level: {args.level}")
    print(f"workflows: {', '.join(selected_workflow_ids)}")
    if args.workflow0_root.strip():
        print(f"workflow0_root: {workflow_roots.get('WF0', os.path.abspath(args.workflow0_root.strip()))}")
    if args.workflow1_root.strip():
        print(f"workflow1_root: {workflow_roots.get('WF1', os.path.abspath(args.workflow1_root.strip()))}")
    print(f"pv_panels: {', '.join(panels)}")
    if building_filter is not None:
        print(f"building_filter: {', '.join(sorted(building_filter))}")
    print("Wrote:")
    for path in outputs_written:
        print(f"  - {path}")


if __name__ == "__main__":
    main()
